### PR TITLE
vnc_base: Prevent 'uninitialized' warning in mouse_move

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by coolo** [comment]
I would rather die than to move to 0,0

**Comment by okurz** [comment]
I wasn't sure if this isn't a valid use case after all.

**Comment by okurz** [comment]
updated to die instead although I am not sure where this will fail.

**Comment by coolo** [comment]
the warning is still there - and I didn't realize what you tried to fix (taking that your originally pushed a null backend with it) ;(

The uninitialized variable is in {mouse} not in the parameter.

**Comment by okurz** [comment]
Sorry for the confusion. I am pretty sure the warning observed was within the parameters of course that could also be true for the mouse object

**Pull request merged**
