### PR TITLE
Remove check for qemu >= 4 in qemu backend

### PR DESCRIPTION
**Pull request by mimi1vx**
This change fixes poo#98946 and also drop support for
distributions older than Leap 15.2 / SLE 15-SP2

### CODE REVIEW

**Comment by asdil12** [comment]
Clickable link for the lazy ones: https://progress.opensuse.org/issues/98946

**Review by Martchus — CHANGES_REQUESTED** [review]
* Please use the full URL to reference to progress tickets. Otherwise accessing them is rather tedious.
* I'm ok with removing the check in our Perl code but I don't think it is necessary or useful to remove the check in `dependencies.yaml` and the `.spec`-file.

**Review by asdil12 — APPROVED** [review]
LGTM

**Comment by asdil12** [comment]
> * Please use the full URL to reference to progress tickets. Otherwise accessing them is rather tedious.
> * I'm ok with removing the check in our Perl code but I don't think it is necessary or useful to remove the check in `dependencies.yaml` and the `.spec`-file.

I think the test was actually moved to the spec as it is now a hard requirement as we don't workaround old qemu odds.

**Review by Martchus — APPROVED** [review]

**Pull request merged**
