### PR TITLE
spec: Add qemu specific convenience sub-packages

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/77905

### CODE REVIEW

**Review by ilausuch — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]
I'm not sure why these should be useful, but I'm gonna guess pulling these in by default has both political and technological problems, so why not

**Comment by okurz** [comment]
> pulling these in by default has both political and technological problems

What do you mean by that? Do you mean that os-autoinst should pull in qemu-x86 by default? This package is not available on all architectures. Also it is only necessary if one wants to run the qemu backend, e.g. not needed when running something like s390x z/VM or IPMI bare metal.

**Review by Martchus — APPROVED** [review]

**Comment by okurz** [comment]
https://build.opensuse.org/package/live_build_log/devel:openQA:TestGithub:OPR-1573/os-autoinst/openSUSE_Factory/x86_64 shows the correctly built packages. The travis CI tests are still pending but also not necessary as they are not impacted by the spec file

**Comment by kalikiana** [comment]
> > pulling these in by default has both political and technological problems
> 
> What do you mean by that? Do you mean that os-autoinst should pull in qemu-x86 by default? This package is not available on all architectures. Also it is only necessary if one wants to run the qemu backend, e.g. not needed when running something like s390x z/VM or IPMI bare metal.

That's exactly what I meant. Doing the right thing is impossible in practice.

**Comment by okurz** [comment]
Well, I still see it as possibility that we can provide some architecture-agnostic helper package in qemu itself

**Pull request merged**
