### PR TITLE
Enlarge visible windows only in fullscreen method

### PR DESCRIPTION
**Pull request by rakoenig**
See ticket: [poo#109795](https://progress.opensuse.org/issues/109795) for details.

### CODE REVIEW

**Comment by okurz** [comment]
@rakoenig please see https://github.com/os-autoinst/os-autoinst/pull/2027#issuecomment-1096613270 and provide a manual verification test where we can see that working in action as we currently don't have automatic CI tests covering that behaviour.

**Review by Martchus — COMMENTED** [review]
Looks good, there's only one typo ("poblems") in the commit message.

**Review by Martchus — APPROVED** [review]

**Comment by rakoenig** [comment]
> @rakoenig Did you see this comment?

Yes I saw it and I'm desperately trying to make a verification run. But so far what people suggested on the Slack-channel didn't work for me. Running the worker in the container was a complete fail. I'm a bit lost on how to tweak the workers from remote, but looks like there is not much of a documentation or even a tutorial about that stuff.

**Comment by okurz** [comment]
@Martchus could you help rakoenig to get this tested?

**Comment by Martchus** [comment]
When I remember the chat history correctly, that change was actually tested (by manually logging in on the host and invoking the command manually). Hence I've also already approved the change.

If it was my PR I'd probably go for the approach documented here: https://progress.opensuse.org/projects/openqav3/wiki/#Use-a-production-host-for-testing-backend-changes-locally-eg-svirt-powerVM-IPMI-bare-metal-s390x-etc - This is the approach used so far when developing with the svirt backend.

Alternatively, you can also hot-patch an instance. [Take it out of production](https://progress.opensuse.org/projects/openqav3/wiki/Wiki#Take-machines-out-of-salt-controlled-production) and apply a patch via `patch -d /usr/lib/os-autoinst -p1 -i …`. To run a test on that specific worker, clone it with the worker-specific `WORKER_CLASS` setting. You don't need to restart any services on the host for os-autoinst changes to apply. When you're done, revert your changes and [bring the worker back](https://progress.opensuse.org/projects/openqav3/wiki/Wiki#Bring-back-machines-into-salt-controlled-production).

(All other suggestions were only luring you into uncharted territory. They might be better in the long run but you'll have to figure out details on your own at this point.)

**Review by okurz — APPROVED** [review]
I am ok if the command was tried out on the actual production machines

**Pull request merged**
