### PR TITLE
Use ipxe kernel to support iBFT

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by aaannz** [comment]
Please update `doc/backend_vars.asciidoc`.

**Comment by dzedro** [comment]
Sorry, didn't know
Updated

**Comment by aaannz** [comment]
I was about to merge this, but noticed [WIP] flag. Still valid?

**Comment by dzedro** [comment]
It is valid, but I found one problem, have to fix it and maybe it will change also this PR

**Comment by coolo** [comment]
I don't see the relation between IBFT and PXE. To me this is like if $vars{FOO} do_bar.

**Comment by dzedro** [comment]
Why relation to PXE ? I mentioned ipxe kernel http://ipxe.org/

**Comment by coolo** [comment]
you load kernel for PXE if IBFT is set - and this connection is only in your head and is very specifc to the scenario you're working on. os-autoinst should be driven to load PXE kernel if e.g. IPXE is set or alike

**Comment by aaannz** [comment]
I guess iPXE kernel is used here to support iSCSI boot. But I agree that as iPXE is quite versatile specific `IPXE` variable makes sense to me.

**Comment by dzedro** [comment]
true, will change that variable name, but IPXE is already used, no idea why is PXE named as IPXE
[https://github.com/dzedro/os-autoinst-distri-opensuse/blob/master/tests/installation/bootloader.pm#L23](url)

**Comment by dzedro** [comment]
I need help, I need to push _-kernel /usr/share/qemu/ipxe.lkrn -append 'dhcp && sanhook --drive 0x80 iscsi:10.100.98.90::3260:1:iqn.2016-01.openqa.de:for.openqa'_  to make IPXE/IBFT work.
for example, if I write it like this:
`        if ($vars->{IIPXE}) {`
 `           push(@params, '-kernel', '/usr/share/qemu/ipxe.lkrn');`
`            push(@params, '-append', "\'config", '&&', 'sanhook', '--drive', '0x80', "$vars->{ISCSI}" . "\'");`
`        }`
Job ends with error:
`12:20:26.4359 QEMU: qemu-system-x86_64: -append 'config: could not open disk image &&: Could not open '&&': No such file or directory`
[http://10.100.98.90/tests/1475/file/autoinst-log.txt](url)

The problem are the quotes I would say, if I try to push just `-append dhcp` it works
, but pushing multiple commands with `&&` or `;` is problem.

Any idea ?

**Comment by coolo** [comment]
the argment to append needs to be in one string.

```
push(@params, '-append', "'config && sanhook --drive 0x80 $vars->{ISCSI}'");

**Comment by dzedro** [comment]
@coolo true :+1: , it's working

**Comment by dzedro** [comment]
I would leave the IBFT variable, I don't see any other test than iBFT test which would use this IPXE kernel and IPXE variable is already used
Any other ideas for variable names are welcome

**Comment by dzedro** [comment]
Or use `NBF;boolean;0;open source network boot firmware e.g. to attach iscsi target on boot http://ipxe.org/` ?

**Comment by coolo** [comment]
you can do much more with the ipxe kernel than just doing iscsi - http://ipxe.org/start

So +1 for using NBF and document iscsi as example

**Comment by dzedro** [comment]
updated with NBF variable

**Pull request merged**
