### PR TITLE
Export TESSDATA_PREFIX in check phase of os-autoinst.spec

### PR DESCRIPTION
**Pull request by mimi1vx**
https://progress.opensuse.org/issues/123193

### CODE REVIEW

**Review by okurz — APPROVED** [review]

**Review by okurz — CHANGES_REQUESTED** [review]
There are multiple error messages and unhandled output in https://github.com/os-autoinst/os-autoinst/actions/runs/3967534141/jobs/6799607859#step:3:618 . Please ensure that there by default is only the single line with the status of 02-ocr.t and not more

**Review by Martchus — APPROVED** [review]
With the changes you've just pushed it works for me locally as well now.

**Comment by mimi1vx** [comment]
> There are multiple error messages and unhandled output in https://github.com/os-autoinst/os-autoinst/actions/runs/3967534141/jobs/6799607859#step:3:618 . Please ensure that there by default is only the single line with the status of 02-ocr.t and not more

.. there was typo in variable settings for CI , now fixed

**Comment by okurz** [comment]
yes, looks good except for the ShellCheck failures you already mentioned:
```
4: Test timeout computed to be: 10000000
4: 
4: In tools/container_run_ci line 33:
4:     -h | --help ) usage 0; shift ;;
4:                            ^----^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
4: 
4: 
4: In tools/invoke-tests line 28:
4:     -h | --help               ) usage;                     shift   ;;
4:                                                            ^------^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
4: 
4: 
4: In tools/tidy line 37:
4:     -h | --help ) usage; shift ;;
4:                          ^----^ SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
4: 
4: For more information:
4:   https://www.shellcheck.net/wiki/SC2317 -- Command appears to be unreachable...
```

**Review by okurz — APPROVED** [review]

**Pull request merged**
