### PR TITLE
Consistent qw usage

### PR DESCRIPTION
**Pull request by coolo**
This is going one step further than @okurz's origina PR

### CODE REVIEW

**Comment by coolo** [comment]
I would like to squash the 2 fixes so we only have one policy commit to destroy git blame

**Comment by okurz** [comment]
+1

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
So I squashed the commits now - it now looks like okurz also did the single quote thingy. If you prefer I reset the author, just tell - but we have to chose one :)

**Comment by okurz** [comment]
reset the author of which commit? It looks like there are two commits, one by you and one by me, but I don't actually care

**Comment by coolo** [comment]
there were 3 originally

**Pull request merged**
