### PR TITLE
Add github actions CI definitions

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/66721

### CODE REVIEW

**Comment by Martchus** [comment]
Unfortunately it fails. Maybe https://progress.opensuse.org/issues/66721#Patch-qemu is required?

**Comment by perlpunk** [comment]
The required patch is already (commented out) in the dockerfile

**Comment by okurz** [comment]
This is interesting:

```
podman run --rm -it --entrypoint '' registry.opensuse.org/devel/openqa/containers/os-autoinst_dev cat /etc/os-release
```

shows openSUSE Leap 15.1, I expected openSUSE Leap 15.2

Seems like we never properly updated the container image we use. I recorded that in
https://progress.opensuse.org/issues/80962
and will try to switch to Tumbleweed in https://github.com/os-autoinst/os-autoinst/pull/1586 but here I will first try a smaller step with going to 15.2 explicitly

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1590#issuecomment-742596504 is a proof that codecov reports are actually uploaded by GHA

**Review by Martchus — COMMENTED** [review]
Looks good… I suppose. The quoting of `'$target'` looks a bit odd at the first look. A comment explaining the difference between codecov and codecovbash and why we sometimes need the latter would make sense.

**Comment by okurz** [comment]
> The quoting of `'$target'` looks a bit odd at the first look.

I know. That's because of nested quoting. Maybe I can do better with `\"`

> A comment explaining the difference between codecov and codecovbash and why we sometimes need the latter would make sense.

Sure. I wonder where to put it, maybe in the "COMMENT" in cmake/test-targets.cmake?

Updated:

* Replaced single ticket quotes within `"` with `\"`
* Added comments explaining codecov and codecovbash in cmake/test-targets.cmake
* Added command line parsing to tools/docker_run_ci

**Review by Martchus — APPROVED** [review]

**Pull request merged**
