### PR TITLE
Forward select_console failures to test process for proper reporting

### PR DESCRIPTION
**Pull request by coolo**
Releated ticket: https://progress.opensuse.org/issues/59267

### CODE REVIEW

**Comment by coolo** [comment]
I hotpatched this on openqaworker2, validation run: https://openqa.suse.de/tests/3581385

**Comment by coolo** [comment]
https://openqa.suse.de/tests/3581465#step/installation_overview/18 correctly fails now.

**Comment by okurz** [comment]
Tests would be nice :)

**Comment by coolo** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1263 shows the bug in master - let's rebase then

**Pull request merged**
