### PR TITLE
docker: Upgrade os-autoinst_dev image to Tumbleweed

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
https://travis-ci.org/github/os-autoinst/os-autoinst/builds/748733306#L1244 shows

```
6: Could not run /usr/bin/ninja update-deps: rc=256 at ./27-make-update-deps.t line 34.
6: ./27-make-update-deps.t .................. 
6: Dubious, test returned 1 (wstat 256, 0x100)
6: No subtests run 
```

I don't know what that means. Maybe https://github.com/os-autoinst/os-autoinst/pull/1589 helps

**Comment by okurz** [comment]
@Martchus is this what you have seen recently elsewhere as well?:

```
6:     # No tests run!
6: 
6: #   Failed test 'No tests run for subtest "load test success when casedir and productdir are relative path"'
6: #   at ./14-isotovideo.t line 200.
6: "/usr/bin/perl" failed to start: "No child processes" at ./14-isotovideo.t line 34.
6: # Tests were run but no plan was declared and done_testing() was not seen.
6: # Looks like your test exited with 255 just after 10.
6: [17:11:51] ./14-isotovideo.t ........................ 
6: Dubious, test returned 255 (wstat 65280, 0xff00)
6: Failed 1/10 subtests 
```

**Comment by kalikiana** [comment]
> @Martchus is this what you have seen recently elsewhere as well?:
> 
> ```
> 6:     # No tests run!
> 6: 
> 6: #   Failed test 'No tests run for subtest "load test success when casedir and productdir are relative path"'
> 6: #   at ./14-isotovideo.t line 200.
> 6: "/usr/bin/perl" failed to start: "No child processes" at ./14-isotovideo.t line 34.
> 6: # Tests were run but no plan was declared and done_testing() was not seen.
> 6: # Looks like your test exited with 255 just after 10.
> 6: [17:11:51] ./14-isotovideo.t ........................ 
> 6: Dubious, test returned 255 (wstat 65280, 0xff00)
> 6: Failed 1/10 subtests 
> ```

I think I was the one bringing this one up. I saw it once in #1611 but couldn't reproduce it. Even running the *subtest* in a loop doesn't reproduce it.

**Comment by Martchus** [comment]
Yes, that's exactly the problem I've seen recently as well. https://github.com/os-autoinst/os-autoinst/pull/1613 contains a fix. I've restarted the CI (which didn't work at all a few hours ago). Let's see whether it passes now.

**Review by kalikiana — APPROVED** [review]

**Pull request merged**
