### PR TITLE
[WIP] Add floppy disk drive

### PR DESCRIPTION
**Pull request by dzedro**
Needed for windows 10 installtion to install scsi drivers otherwise windows can't see scsi disk

http://10.100.98.90/tests/2093/modules/win10/steps/2

https://hackweek.suse.com/14/projects/1468

Yes I tried to use usb, maybe I did something wrong but more different tries didn't windows see

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
and where did you get that fdd image from? I would like to see some documentation - i.e. in docs/backend_vars

**Comment by dzedro** [comment]
sorry, updated

**Comment by coolo** [comment]
damn, now I merged it as WIP

**Comment by dzedro** [comment]
no FDD, thank god
FDD doesn't work with UEFI, I used ide-cd ISO

**Comment by dzedro** [comment]
I was just goind to close this PR with comment above :D

**Comment by dzedro** [comment]
I will revert it ;)

**Comment by dzedro** [comment]
http://10.100.98.90/tests/overview?distri=sle&version=12-SP2&build=1&groupid=2

**Pull request merged**
