### PR TITLE
VNC: Handle temporarily unavailable socket during reconnect gracefully

### PR DESCRIPTION
**Pull request by okurz**
Verification run: http://lord.arch/tests/6557#step/reconnect_s390/4

Related progress issue: https://progress.opensuse.org/issues/19262

### CODE REVIEW

**Comment by okurz** [comment]
need to cover more locations for access to the socket, waitfor http://lord.arch/tests/6535

**Comment by coolo** [comment]
But we are not supposed to be graceful - having a dead VNC for 8 seconds and counting is fatal.

**Comment by okurz** [comment]
yes, but you turned it into a backend problem causing the job to be incomplete. This will make it not show up in list of previous jobs, make investigation harder and carry over of issues does not work. I am not fixing the dead VNC but turning it into a fail because I consider it an issue of either the tests or the product.

The VNC stall detection is undef'ing the socket variable and other methods try to access it. I consider that wrong from the perspective of the backend itself.

**Comment by coolo** [comment]
You are not turning it into a fail, you are turning it into a pass. Your test just happens to fail later.

**Comment by okurz** [comment]
The VNC stall detection is undef'ing the socket variable and other methods try to access it. Don't you consider this wrong?

**Comment by coolo** [comment]
I didn't say the code is bugfree, I said your PR is wrong

**Comment by okurz** [comment]
the usual coolo …

In https://github.com/os-autoinst/os-autoinst/pull/810/files#diff-1e0c5a0ad8e4c4789e337e7ac95822afL838 you added code to close (and delete) the socket and then IIUC call "login" which is reconnecting the VNC console. So the process shouldn't die here, am I wrong?

**Comment by coolo** [comment]
The process should die if it can't relogin - if you can, handle it as failure. But in general it's an incomplete as something is wrong with the system.

The real failure is in the tests though as the dying VNC is not closed. So far this is only done in shutdown

**Comment by okurz** [comment]
> The process should die if it can't relogin

so in case the relogin was successful the other sockets should have never been accessed?

**Comment by okurz** [comment]
The fix for the failing s390x tests is in but I still consider this PR very useful to not have hidden incompletes with no useful carry over. This change would not fix the failures but should make them much more obvious and easier to fix.

**Comment by sysrich** [comment]
The inability to reconnect to VNC puts the test into an inconsistent and undefinable state.

Ignoring that (as this PR does) and attempting to proceed regardless then relies on proceeding tests to fail as expected

I do not agree this PR is a good idea, it encorages bad behaviour in the backend and requires tests to hold additional logic to handle the potential variables.

It might work for the examples in the PR, but the code in question is used in countless other scenarios, and on that ground i agree with @coolo and give my -1

The job of the backend is to do what it can to provide a consistent framework for tests to run on top, when we detect a failure of the key part of that infrastructure, we shouldn't ignore it and expect the tests to be able to cope with such stupidity.

**Comment by okurz** [comment]
ok, then I guess "dying" in all instances with a proper message is better. What is taking quite some time for reviewers is that incompletes don't show anything useful in the details tab. The whole last module is always missing and never uploaded and one needs to know what to look for in os-autoinst. At best we have a `record_info` screen burning into the user's eyes with an obvious "This is how the test is wrong"-frame :-)

**Comment by coolo** [comment]
I agree, it's just not so easy to communicate between backend and testapi process. Perhaps some 'final words?' callback? :)

**Comment by okurz** [comment]
Basically using the same die handler as for test code itself should work.

**Comment by coolo** [comment]
if the die was in testapi process, yes.

**Pull request closed without merging**
