### PR TITLE
t : Add missing letter in test data

### PR DESCRIPTION
**Pull request by KevinKipkorir**
Added missing letter in test data

### CODE REVIEW

**Comment by perlpunk** [comment]
Please have a look at https://chris.beams.io/posts/git-commit/ for general suggestions :)
We usually prefix commits in tests with `t:`.
So how about `t: Add missing letter in test data`

**Comment by okurz** [comment]
Hi @KevinKipkorir welcome and congrats for your first contribution. You really managed to find a literal "missing letter" . This is actually impressive and also funny 😂 trust me, we have not hidden that missing letter as a riddle, you found it anyway ;) I think it's a good idea to follow the suggestion from @perlpunk and update the git commit message which is a good next exercise how to update a commit and push an update to github

**Comment by Martchus** [comment]
Please rebase your commits; never have a merge commit on your PR branch.

**Comment by KevinKipkorir** [comment]
Added missing letter in the test data

**Comment by Martchus** [comment]
It looks like you've now rebased it against the wrong commit and I cannot even see your actual commit anymore. (If something got lost you can use `git reflog` to find old commits and use the ref to reset your branch to a previous state.)

**Comment by Martchus** [comment]
Btw, `git pull --rebase origin master` would have done it.

**Pull request closed without merging**
