### PR TITLE
Allow checking journal for known bugs

### PR DESCRIPTION
**Pull request by asdil12**
https://progress.opensuse.org/issues/46988

### CODE REVIEW

**Comment by coolo** [comment]
I don't want to have package specific details in the test api, find a way to hook this in the distribution.

**Comment by coolo** [comment]
(and yes, systemd is a package)

**Comment by coolo** [comment]
Actually I see 0 reason to have this in the testapi. it's plainly in the test itself.

**Comment by Martchus** [comment]
I'm afraid @coolo is right. Or prevents you something from having this in the test distribution?

**Pull request closed without merging**
