### PR TITLE
also record matched needles that are not the best match

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by coolo** [comment]
this way you still miss needles - the first time they are best and then the 3rd needle will replace $best, but $secondbest is lost between the chairs

**Comment by lnussel** [comment]
I think L138 handles that

**Comment by coolo** [comment]
Yeah. But I wonder if we can't get some sorting into the needles with the same level of matching - or we might keep 2 needles created in parallel forever

**Comment by coolo** [comment]
see https://github.com/os-autoinst/os-autoinst/pull/322

**Pull request merged**
