### PR TITLE
Fix the readout of git hash as version when called from other directory

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@foursixnine ?

**Comment by foursixnine** [comment]
I just wonder, what was the motivation for this... But good catch?

**Comment by okurz** [comment]
uhm, doesn't the subject line explain this? When calling the isotovideo of a local git checkout but from another directory, e.g. when starting an openQA worker with the `--isotovideo` parameter, previously the git command would not be executed in the correct folder.

**Comment by foursixnine** [comment]
> uhm, doesn't the subject line explain this? 

It explain what's being fixed.

> 

When calling the isotovideo of a local git checkout but from another directory, e.g. when starting an openQA worker with the --isotovideo parameter, previously the git command would not be executed in the correct folder.

This is how I run openQA locally, but I've never paid attention to the actual version reported, so that could be it.

**Pull request merged**
