### PR TITLE
Add current_console method

### PR DESCRIPTION
**Pull request by foursixnine**
With changes introduced in c670720 testapi no longer holds what is the
current console, leading to problems when test distributions rely on
this.

### CODE REVIEW

**Comment by richiejp** [comment]
You could also refactor `is_serial_terminal`, `console` etc. to use the new function :-p

**Comment by foursixnine** [comment]
@richiejp good point!

**Comment by foursixnine** [comment]
I wonder why codecov is complaining that there are no lines being covered...

**Comment by mudler** [comment]
We need to look at it, but it should boil down to Devel::Cover that must be called from each involved process :(

**Comment by foursixnine** [comment]
\o/ Coverage slowly going up!

**Pull request merged**
