### PR TITLE
Add python binding/import/wrapper for mmapi and lockapi

### PR DESCRIPTION
**Pull request by askebm**
Adding python bindings for lockapi and mmapi allows for managing multi machine tests in python.
 
An example test could look like this
``` python
import lockapi
import mmapi

def run(self):
    lockapi.mutex_create('foomutex')
    lockapi.mutex_lock('foomutex')
    lockapi.mutex_unlock('foomutex')
    lockapi.mutex_wait('foomutex')

    # wait for child jobs to be done
    mmapi.wait_for_children()
```

### CODE REVIEW

**Review by Martchus — COMMENTED** [review]
I guess this is good - although it works probably preferable to generate those files via a CMake template to avoid the repetition. (But we can do this in a separate PR.)

Have you checked whether those files are going to be installed? If not then you probably need to add them to the CMake install target.

**Comment by askebm** [comment]
> Have you checked whether those files are going to be installed? If not then you probably need to add them to the CMake install target.

I had just looked in `dist/rpm/os-autoinst.spec` and seen the  `%{_prefix}/lib/os-autoinst/*.py` glob.

I have added it to the `CMakeLists.txt`

The output of `make test-installed-files` for completeness
```
ninja -C /home/abm/git/os-autoinst/build test-installed-files
ninja: Entering directory `/home/abm/git/os-autoinst/build'
[1/1] cd /home/abm/git/os-autoinst/build && /usr/bin/ctest -V -R test-installed-files
UpdateCTestConfiguration  from :/home/abm/git/os-autoinst/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/abm/git/os-autoinst/build/DartConfiguration.tcl
Test project /home/abm/git/os-autoinst/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: test-installed-files

1: Test command: /home/abm/git/os-autoinst/tools/check-installed-files "/usr/bin/ninja"
1: Working Directory: /home/abm/git/os-autoinst/build
1: Test timeout computed to be: 10000000
1: [0/1] Install the project...
1: -- Install configuration: ""
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/bin/debugviewer
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/bin/snd2png
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/lib/perl5/5.38/vendor_perl/auto/tinycv/tinycv.so
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/lib/perl5/5.38/vendor_perl/tinycv.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/videoencoder
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/bin/isotovideo
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/share/doc/packages/os-autoinst/README.asciidoc
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/share/doc/packages/os-autoinst/COPYING
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/share/doc/packages/os-autoinst/basetest.html
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/share/doc/packages/os-autoinst/testapi.html
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/autotest.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/amt.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/baseclass.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/console_proxy.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/driver.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/generalhw.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/ipmi.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/null.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/pvm_hmc.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/qemu.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/s390x.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/spvm.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/svirt.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/vagrant.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/backend/virt.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/basetest.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/bmwqemu.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/commands.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/amtSol.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/console.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/ipmiSol.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/localXvnc.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/network_console.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/s3270.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/serial_screen.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshIucvconn.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/ssh_screen.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshSerial.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshVirtsh.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshVirtshSUT.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshX3270.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshXtermIPMI.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/sshXtermVt.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/ttyConsole.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/video_base.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/video_stream.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/virtio_terminal.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/vnc_base.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/VNC.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/VMWare.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/distribution.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/lockapi.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/log.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/mmapi.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/myjsonrpc.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/needle.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/ocr.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Benchmark/Stopwatch.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Commands.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Exceptions.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Isotovideo/Backend.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Isotovideo/CommandHandler.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Isotovideo/Interface.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Isotovideo/NeedleDownloader.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Isotovideo/Runner.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Isotovideo/Utils.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/NamedIOSelect.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/BlockDevConf.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/BlockDev.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/ControllerConf.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/DriveController.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/DriveDevice.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/DrivePath.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/MutParams.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/PFlashDevice.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/Proc.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/SnapshotConf.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Qemu/Snapshot.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/OpenQA/Test/RunArgs.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/osutils.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/signalblocker.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/testapi.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/consoles/icewm.cfg
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/crop.py
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/lockapi.py
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/mmapi.py
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/testapi.py
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/dell_e6330/smbios_type_1.bin
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/dell_e6330/smbios_type_2.bin
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/dell_e6330/smbios_type_3.bin
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/hp_elitebook_820g1/smbios_type_1.bin
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/hp_elitebook_820g1/smbios_type_2.bin
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/hp_elitebook_820g1/smbios_type_3.bin
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dmidata/dump
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/cv.pm
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/schema/Wheels-01.yaml
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/check_qemu_oom
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/dewebsockify
1: -- Installing: /tmp/tmp.bD7lBYQHUb/usr/local/lib/os-autoinst/vnctest
1/1 Test #1: test-installed-files .............   Passed    0.11 sec

The following tests passed:
        test-installed-files

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.11 sec
```

**Review by okurz — CHANGES_REQUESTED** [review]
Hi @askebm , welcome to this project for your first-time contribution :1st_place_medal:  :)

I wonder how you came to this change. What did you want to achieve and how do you test that your change is doing what you expect? It would be best if you can clarify this in your actual git commit message to explain the change.

And I second what @Martchus stated in https://github.com/os-autoinst/os-autoinst/pull/2505#pullrequestreview-2127447752 that it would be better to use automatic generation however the files are simple and static enough that probably we are ok to accept the current version.

**Review by okurz — APPROVED** [review]
Looks all good. Great!

**Review by Martchus — APPROVED** [review]
I assume you have tested this somehow.

**Pull request merged**
