### PR TITLE
Make qcow images self-contained by compression

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/17790

### CODE REVIEW

**Comment by foursixnine** [comment]
I would change the commit message to explicitly say that compression is being enabled by default.

**Comment by okurz** [comment]
done

**Comment by foursixnine** [comment]
LGTM

**Comment by aaannz** [comment]
For uploading we have threshold 1000 second so compressing should not trigger dead worker issue. Fine by me.

**Pull request merged**
