### PR TITLE
Wait a second before and after typing

### PR DESCRIPTION
**Pull request by dzedro**
This would solve lot of issues, depends how slow/safe/human we want to be to avoid race condition e.g. https://progress.opensuse.org/issues/13766

### CODE REVIEW

**Comment by okurz** [comment]
just in before the wait_screen_change option was added. I would suggest to test if this helps already or if we should add your proposal, but as optional, not mandatory in all cases.

**Comment by AdamWill** [comment]
nack. please don't do this. The right way to do this is to put it in your distro-specific high-level functions - `type_slowly` or `type_very_slowly` or whatever they're called.

I already wrote `type_safely` and `type_very_safely` functions for Fedora which use the 'wait for screen change between character sets' feature we recently added to `type_string` *and* `wait_still_screen` - but for longer - after typing; if you do this, those will just be stacking `wait_still_screen` calls on top of each other with *no way* to avoid it.

IMHO `type_string`'s basic behaviour is too longstanding to make drastic changes like this unconditionally. At the very least any change like this should be optional and not the default.

**Comment by AdamWill** [comment]
Also consider the case where we're typing into a screen which changes constantly (in Fedora, for e.g., we test the cockpit webapp, which handily shows a constantly-scrolling graph all the damn time). The `type_string` will now waste 10 seconds.

**Comment by coolo** [comment]
we need to come up with a good solution to make this more reliable, but slowing down everything is not the solution, no

**Pull request closed without merging**
