### PR TITLE
Check exit code when running qemu-img

### PR DESCRIPTION
**Pull request by perlpunk**
If the command failed, there will be no JSON to parse

Issue: https://progress.opensuse.org/issues/64854

### CODE REVIEW

**Comment by okurz** [comment]
Test looks good but could you please provide example runs of how the complete output of `isotovideo` would look like in the case of error or no-error? E.g. I would look for no duplication of error messages and such.

**Comment by perlpunk** [comment]
@okurz 
```
[2020-03-26T16:22:40.235 CET] [debug] running /usr/bin/chattr -f +C /home/tina/openqa-devel/openqa/pool/1/raid
[2020-03-26T16:22:40.248 CET] [debug] running /usr/bin/qemu-img info --output=json openSUSE_Krypton.x86_64-5.12.80-Build16.72.iso
[2020-03-26T16:22:40.256 CET] [debug] qemu-img: Could not open 'openSUSE_Krypton.x86_64-5.12.80-Build16.72.iso': Could not open 'openSUSE_Krypton.x86_64-5.12.80-Build16.72.iso': No such file or directory
[2020-03-26T16:22:40.256 CET] [debug] Backend process died, backend errors are reported below in the following lines:
qemu-img command failed at /home/tina/openqa-devel/repos/os-autoinst/OpenQA/Qemu/Proc.pm line 142.

[2020-03-26T16:22:40.256 CET] [info] ::: OpenQA::Qemu::Proc::save_state: Saving QEMU state to qemu_state.json
[2020-03-26T16:22:40.257 CET] [debug] flushing frames
[2020-03-26T16:22:40.478 CET] [debug] sending magic and exit
[2020-03-26T16:22:40.479 CET] [debug] received magic close
[2020-03-26T16:22:40.480 CET] [debug] backend process exited: 0
failed to start VM at /home/tina/openqa-devel/repos/os-autoinst/backend/driver.pm line 141.
[2020-03-26T16:22:41.481 CET] [debug] terminating command server 23273 because test execution ended through exception
[2020-03-26T16:22:42.483 CET] [debug] done with command server
[2020-03-26T16:22:42.483 CET] [debug] stopping autotest process 23277
[2020-03-26T16:22:43.485 CET] [debug] done with autotest process
23268: EXIT 1
[2020-03-26T16:22:43.0542 CET] [info] [pid:20622] Isotovideo exit status: 1
[2020-03-26T16:22:43.0563 CET] [info] [pid:20622] +++ worker notes +++
[2020-03-26T16:22:43.0563 CET] [info] [pid:20622] End time: 2020-03-26 15:22:43
[2020-03-26T16:22:43.0563 CET] [info] [pid:20622] Result: died: terminated prematurely, see log output for details
[2020-03-26T16:22:43.0567 CET] [info] [pid:23298] Uploading video.ogv
[2020-03-26T16:22:43.0588 CET] [info] [pid:23298] Uploading video_time.vtt
[2020-03-26T16:22:43.0603 CET] [info] [pid:23298] Uploading vars.json
[2020-03-26T16:22:43.0618 CET] [info] [pid:23298] Uploading autoinst-log.txt
```

**Comment by okurz** [comment]
ok, we might need to change the format soon because we have an error string *above* "Backend process died" and one *below* with "qemu-img command failed". But the JSON error is averted.

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1376 is addressing https://github.com/os-autoinst/os-autoinst/pull/1370#issuecomment-604496720

**Pull request merged**
