### PR TITLE
Adapt script_run to return exit code if waiting for finish

### PR DESCRIPTION
**Pull request by aaannz**
needed for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1374

### CODE REVIEW

**Comment by coolo** [comment]
24 days? Not bad :)

But :+1:

**Comment by aaannz** [comment]
Drafted during openQA hackaton :)

**Comment by aaannz** [comment]
I'll make one small modification to this as I don't handle situation when we are waiting for a finish, but timeout. In that case I'll return undef. I'll also change return value when not waiting from 0 to undef.

**Comment by okurz** [comment]
nice :-)

**Pull request merged**
