### PR TITLE
introduce CDDMODEL

### PR DESCRIPTION
**Pull request by lnussel**
aarch64 needs a way to use virtio cd

### CODE REVIEW

**Comment by coolo** [comment]
this code is getting seriously out of control ;(

**Comment by coolo** [comment]
and there is a D too much in your commit log

**Comment by aplanas** [comment]
Clearly we need a XML definition for qemu configuration.  This XML can also have different backends (real hardware, kvm, vbx, qemu, vmware, ...)

... oh wait http://libvirt.org/

**Comment by coolo** [comment]
do you know someone in the cloud team by chance? :)

**Pull request merged**
