### PR TITLE
Use Test::Warnings where possible to prevent warnings in tests

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by Martchus** [comment]
please rebase

**Comment by coolo** [comment]
why did you change the documentation? This looks out of place for this PR

**Comment by okurz** [comment]
Reverted the documentation changes. I am not sure about the coverage report. Do we demand coverage to hit changed code paths now? Well, I can try

**Comment by coolo** [comment]
devel::coverage is none of my favorite modules

**Pull request merged**
