### PR TITLE
Adapt zKVM QEMURAM default to match other archs

### PR DESCRIPTION
**Pull request by Soulofdestiny**

### CODE REVIEW

**Comment by okurz** [comment]
as this is only setting the default value if not already set, what about not setting a default at all and using `get_required_var`?

**Comment by Soulofdestiny** [comment]
Well, I like the approach to have a default value more, because then you don't need to care about setting the variable in every single testcase, but only in the testcases you need specific values

**Comment by okurz** [comment]
discussed with mgriessmeier:
Currently the value of QEMURAM is only set as override in some test_suites or machines, by default this value here is the value being used. As "1024MB" is a sane default not only for anything openSUSE or SUSE specific I +1 this commit. Anyway, to DRY I recommend to extract setting this value to a common baseclass for qemu and other virtual machine backends and set the default from there, probably the same for HDD size. Setting this value can also be done as "product specific" from the tests distribution, e.g. based on what has been documented as the default for the product we test.

**Comment by aaannz** [comment]
:+1:

**Comment by okurz** [comment]
See #518 for an alternative approach.

**Comment by sysrich** [comment]
:+1:

**Comment by coolo** [comment]
this is obsolete now, right?

**Comment by Soulofdestiny** [comment]
should be -> #518

**Pull request closed without merging**
