### PR TITLE
Downgrade libslirp0 in CI env to fix network in SUT

### PR DESCRIPTION
**Pull request by Martchus**
* See https://progress.opensuse.org/issues/110196
* See https://bugzilla.suse.com/show_bug.cgi?id=1198773

### CODE REVIEW

**Review by kalikiana — APPROVED** [review]

**Comment by Martchus** [comment]
It doesn't work. Considering I cannot even find "slirp" in the logs at all I likely just did it wrong. (So this isn't disapproving my theory that libslirp0 is the culprit yet.)

**Comment by Martchus** [comment]
I suppose it worked:

```
The following package is going to be downgraded:
  libslirp0

1 package to downgrade.
Overall download size: 61.4 KiB. Already cached: 0 B. After the operation, 8.0 B will be freed.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libslirp0-4.3.1-1.51.x86_64 (1/1),  61.4 KiB (125.5 KiB unpacked)
Retrieving: libslirp0-4.3.1-1.51.x86_64.rpm [done]

Checking for file conflicts: [....done]
(1/1) Installing: libslirp0-4.3.1-1.51.x86_64 [..............done]
…
 7: [14:44:52] ./36-openqa-namedioselect.t .............. ok      307 ms ( 0.00 usr  0.00 sys +  0.28 cusr  0.03 csys =  0.31 CPU)
7: [14:44:55] ./44-scripts.t ........................... ok     2828 ms ( 0.00 usr  0.00 sys +  2.47 cusr  0.39 csys =  2.86 CPU)
7: [14:48:42] ./99-full-stack.t ........................ ok   226640 ms ( 0.06 usr  0.02 sys + 48.10 cusr  3.73 csys = 51.91 CPU)
7: [14:48:42]
7: All tests successful.
7: Files=59, Tests=1266, 444 wallclock secs ( 0.67 usr  0.15 sys + 243.08 cusr 21.48 csys = 265.38 CPU)
7: Result: PASS
```

---

However, now codecov is broken:

```
[2/3] cd /opt && /opt/tools/invoke-tests --coverage --skip-if-cover-db-exists --prove-tool /usr/bin/prove --make-tool /usr/bin/ninja --build-directory /opt/build
[3/3] cd /opt && /usr/bin/cover -report codecovbash /opt/build/cover_db
FAILED: CMakeFiles/coverage-codecovbash 
cd /opt && /usr/bin/cover -report codecovbash /opt/build/cover_db
Error: codecovbash is not a recognised output format
Can't locate Devel/Cover/Report/Codecovbash.pm in @INC (you may need to install the Devel::Cover::Report::Codecovbash module) (@INC contains: /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at (eval 12) line 1.
BEGIN failed--compilation aborted at (eval 12) line 1.
```

Judging by the log we only attempt to install `Devel::Cover::Report::Codecov`:
```
…
 'perl-Devel-Cover' providing 'perl(Devel::Cover)' is already installed.
…
'perl-Pod-Coverage' providing 'perl(Pod::Coverage)' is already installed.
…
'perl-Devel-Cover-Report-Codecov' providing 'perl(Devel::Cover::Report::Codecov)' is already installed.
```

But my additional `zypper install` shouldn't have caused this (and didn't according to the log). Very strange.

**Comment by perlpunk** [comment]
I think there is an unrelated problem which might cause the codecov one:
```
2022-04-27T14:40:22.8205492Z Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata [.....................................error]
2022-04-27T14:40:22.8216867Z Repository 'Update repository with updates from SUSE Linux Enterprise 15' is invalid.
2022-04-27T14:40:22.8217479Z Warning: Skipping repository 'Update repository with updates from SUSE Linux Enterprise 15' because of the above error.
2022-04-27T14:40:22.8275959Z [repo-sle-update|http://download.opensuse.org/update/leap/15.3/sle/] Valid metadata not found at specified URL
2022-04-27T14:40:22.8280378Z History:
2022-04-27T14:40:22.8281514Z  - File './repodata/5fe599f3bc4189e5aa978e1697de6dda5754dea159e79852cf94b36cf6e5f07d-updateinfo.xml.gz' not found on medium 'http://download.opensuse.org/update/leap/15.3/sle/'
2022-04-27T14:40:22.8282329Z  - Can't provide ./repodata/5fe599f3bc4189e5aa978e1697de6dda5754dea159e79852cf94b36cf6e5f07d-updateinfo.xml.gz
2022-04-27T14:40:22.8282628Z 
```

**Comment by Martchus** [comment]
Ah, so just a repo refreshing error (which unfortunately can happen). I re-triggered the tests and they now passed. So I suppose this PR can be merged. I've just amended the commit to include the relevant progress and bugzilla tickets.

**Review by perlpunk — APPROVED** [review]

**Comment by perlpunk** [comment]
It failed again because of the refresh, I retriggered

**Pull request merged**
