### PR TITLE
Simplify some code in baseclass

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
This is a rather trivial PR to crosscheck the new development base image based on Tumbleweed, see https://progress.opensuse.org/issues/80962 for details

**Comment by kalikiana** [comment]
```
Repository 'qemu' is invalid.
Retrieving repository 'qemu' metadata [.error]
[qemu|http://download.opensuse.org/repositories/devel:/openQA:/ci/openSUSE_Leap_] Valid metadata not found at specified URL
History:
 - [qemu|http://download.opensuse.org/repositories/devel:/openQA:/ci/openSUSE_Leap_] Repository type can't be determined.
```
🤔

**Review by Martchus — APPROVED** [review]

**Comment by Martchus** [comment]
The approval counts for the code changes. If the CI is broken that should be fixed of course.

**Comment by okurz** [comment]
thanks guys for taking a look. I realized some parts missing which I try to fix in https://github.com/os-autoinst/os-autoinst/pull/1618

**Review by Martchus — APPROVED** [review]

**Comment by okurz** [comment]
mergify misses the status from codecov but there is a comment from codecov. Maybe it's a one-off, maybe it's a start of a change we need to fix everywhere

**Comment by okurz** [comment]
I amended a git commit to retrigger checks. Let's see if this also retriggers a codecov check

**Comment by okurz** [comment]
ok, that worked :)

**Pull request merged**
