### PR TITLE
Always log to autoinst-log.txt

### PR DESCRIPTION
**Pull request by asdil12**
Even when also logging to stderr

https://progress.opensuse.org/issues/52235

### CODE REVIEW

**Comment by asdil12** [comment]
Actually nothing but running the testsuite

**Comment by asdil12** [comment]
Ok - I now managed to test it and it works.

**Comment by pevik** [comment]
@Martchus Not only that this PR duplicate logging on every single output line (as noted in https://github.com/os-autoinst/os-autoinst/pull/1161) it also breaks (at least some) s390x builds:
http://quasar.suse.cz/tests/2853#step/bootloader_zkvm/28

**Comment by pevik** [comment]
@Martchus  with manual change from https://github.com/os-autoinst/openQA/pull/2092/files it's working again also for s390x builds. So no need to revert it (e.g. https://github.com/os-autoinst/os-autoinst/pull/1161 is not needed).

**Pull request merged**
