### PR TITLE
consoles: vnc_base: Make sure 'mouse_set' can also be called to hide in corner

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
I didn't think more deeply about this if it makes sense but could help with problems like https://tortuga.suse.de/tests/390#step/xfce_lightdm_logout_login/8

**Comment by coolo** [comment]
I think providing defaults here is wrong. but changing if ($x) to if (defined $x) and providing a more specific warning is more accurate

**Comment by okurz** [comment]
"a more specific warning" should be a `die` because otherwise we will ignore it, right?

**Comment by coolo** [comment]
if you ask me to choose: a die would be better than a silent return

**Comment by okurz** [comment]
upated with explicit die

**Comment by aaannz** [comment]
LGTM

**Comment by aaannz** [comment]
Since  this can break some tests let's discuss when to merge this on next call.

**Pull request merged**
