### PR TITLE
Get rid of wait_idle

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/5830

### CODE REVIEW

**Comment by mnowaksuse** [comment]
This is an API change. I don't thing we want it.

**Comment by okurz** [comment]
I understood we do want it. More than a year ago we added an ugly backtrace to each call of wait_idle to mark it as deprecated. As os-autoinst-distri-opensuse now forbids use of `wait_idle` I guess this is the way to go. Only open point is if we want to have it now or a bit later.

**Comment by sysrich** [comment]
While I agree with the recommendation not to use wait_idle, I accept we live in a real world and within it sometimes people need to do things that are not recommended

wait_idle is one of those cases

life is not binary. Just because something is bad, doesn't mean it doesn't have a right to exist.

-1; Because wait_idle is useful for those times when it doesn't cause problems.

**Comment by okurz** [comment]
@sysrich there is now even a rule in os-autoinst-distri-opensuse preventing to use `wait_idle` at all and we have https://progress.opensuse.org/issues/5830 that states we want to get rid of `wait_idle`.
This is also why @coolo in commit 7e44b202 added a `cluck` to track all uses of `wait_idle`. So you want to
1) go forward and clean it up properly
1) keep the removal in an eternal limbo state
2) rollback changes and go forward implementing wait_idle properly for all backends where I don't have any idea how that would work reliably

**Comment by sysrich** [comment]
@okurz and you've checked with @AdamWill that fedora are not using the API call?
Or how about KDE neon?
Or the YaST team?

I am not comfortable with being cavalier about removing something which we, as an upstream, have a responsibility to provide until we're sure it's at least reasonably painless for our wider community

Your rules for your test repo are of zero relevance to anyone else, openQA is not the sole domain of SUSE QA SLE.

**Comment by AdamWill** [comment]
[adamw@adam os-autoinst-distri-fedora (staging)]$ grep -R wait_idle *
    lib/fedoradistribution.pm:use testapi qw(send_key type_string wait_idle assert_screen);
    lib/fedoradistribution.pm:    wait_idle 5; # because of KDE dialog - SUSE guys are doing the same!
    lib/packagetest.pm:    wait_idle 20;
    tests/disk_guided_encrypted.pm:    wait_idle 5;
    tests/desktop_browser.pm:    wait_idle 5;
    tests/desktop_browser.pm:    wait_idle 3;
    tests/desktop_browser.pm:    wait_idle 2;
    tests/desktop_browser.pm:    wait_idle 2;

**Comment by AdamWill** [comment]
our distri is in pagure: https://pagure.io/fedora-qa/os-autoinst-distri-fedora . pagure works a lot like github. if someone wants to send a PR to replace those `wait_idle` calls, we'll certainly look at it. doing it myself would not be my highest priority right now.

**Comment by okurz** [comment]
I did not think about KDE neon, true. Do you know where their repo would be?

**Comment by sysrich** [comment]
@okurz I don't know..ask jriddell?

**Comment by coolo** [comment]
Suggested compromise: replace wait_idle with a sleep 19 as we do for !qemu backends and leave the carp.

**Comment by okurz** [comment]
agreed, updated accordingly.

**Pull request merged**
