### PR TITLE
Support arbitrary options for '-netdev user'

### PR DESCRIPTION
**Pull request by mnowaksuse**
For FATE#319639 we need to test that YaST2 uses in installation hostname
from network. One way to test it is by -netdev user,hostname=MyHostName
Qemu option.

Test case:

    start qemu with -netdev user,hostname=
    start installation ifcfg=*=dhcp
    check whether hostname is set to 'myhostname1'

Verification:

    # ps aux | grep hostnameXXX
    _openqa+ 13293 13.1  0.1 5074336 45956 ?       Sl   16:35   0:00
    /usr/bin/qemu-system-x86_64 -serial file:serial0 -soundhw ac97
    -global
    isa-fdc.driveA= -vga cirrus -m 4096 -cpu qemu64 -netdev
    user,id=qanet0,hostname=myhostnameXXX

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
fine for me too.

**Comment by okurz** [comment]
@coolo can you then please merge because I can't?

**Comment by coolo** [comment]
I wanted to give some more time to review - it's not like we're going to deploy any minute

**Pull request merged**
