### PR TITLE
Add script/check_qemu_oom to fully covered paths on codecov

### PR DESCRIPTION
**Pull request by Wabri**
The script is already covered 100%

https://progress.opensuse.org/issues/174229

### CODE REVIEW

**Review by perlpunk — APPROVED** [review]

**Review by baierjan — APPROVED** [review]

**Comment by perlpunk** [comment]
That's a new one:
https://github.com/os-autoinst/os-autoinst/actions/runs/12355213371/job/34478308041?pr=2592#step:4:68
```
error - 2024-12-16 15:06:14,883 -- Report creating failed: {"message":"Token required because branch is protected"}
```
Let's see what happens if I retrigger

**Comment by Wabri** [comment]
@perlpunk It happened again, with the same result! Maybe some tokens have expired?

**Comment by perlpunk** [comment]
> It happened again, with the same result! Maybe some tokens have expired?

Where did it happen again? Please add a link

**Comment by Wabri** [comment]
false alarm, I saw the notification and I thought it failed again, but it was an old notification!

**Pull request merged**
