### PR TITLE
Require ffmpeg during tests

### PR DESCRIPTION
**Pull request by baierjan**
Reference: https://progress.opensuse.org/issues/166664

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
I don't understand the reason. Also I would be careful with such approach because skipping tests can lead to unnoticed test degradation.

**Comment by baierjan** [comment]
> I don't understand the reason. Also I would be careful with such approach because skipping tests can lead to unnoticed test degradation.

`backend::baseclass::_ffmpeg_banner` is a direct call `ffmpeg -version` which only make sense if `ffmpeg` is installed

**Comment by baierjan** [comment]
I guess as an alternative we could force installation of ffmpeg in our testing environment (it is not there as it is only a recommended dependency). Not sure what else we can do here, what do you think?

**Comment by okurz** [comment]
> I guess as an alternative we could force installation of ffmpeg in our testing environment (it is not there as it is only a recommended dependency). Not sure what else we can do here, what do you think?

Yes, forcing the installation for test environments makes sense to me

**Comment by baierjan** [comment]
So I guess that could be as simple as adding to the test requirements?

**Review by okurz — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Pull request merged**
