### PR TITLE
spec: use 'check-doc' Makefile target, not 'check'

### PR DESCRIPTION
**Pull request by AdamWill**
The 'check' Makefile target basically runs code quality checks
then runs the 'check-doc' target (which runs spellchecks) as
long as CHECK_DOC isn't 0. In the RPM spec, we're calling 'make
check', but before that, we are hackily disabling all the code
quality checks, so all the 'check' target winds up doing is
calling 'check-doc' (except for SLE, where we set CHECK_DOC=0
because SLE doesn't have the necessary deps). I think it'd make
more sense to drop use of the 'check' target entirely, and just
call 'check-doc' directly when we want to do the spellchecks.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

### CODE REVIEW

**Comment by AdamWill** [comment]
So, what change are you requesting?

**Comment by okurz** [comment]
Well, the extreme cases are: 1. Close PR without any changes or 2. overrule me :)

I would prefer if we still call `make check`. If you have a good idea how to do that but still keep a part of your idea then change accordingly. If not, maybe I have missed what other benefit your PR has?

**Comment by AdamWill** [comment]
I mean, I guess the thing I'm wondering is, what do you envisage potentially being a thing that should be put in `make check` and not `make test`, but which should be run on package builds? What do you see as the distinction between `check` and `test` exactly?

**Comment by okurz** [comment]
Good question. If it wouldn't be for autotools I would ditch "check" in favor of "test" completely

**Comment by Martchus** [comment]
I suppose this PR is no longer required.

I've changed it to `%cmake_build check-pkg-build` which should behave similar to the change proposed here: The CMake build script will automatically conduct the spell checking via that target if `podspell/spell` are installed. (If that's not the case a status message is logged during the configuration stating that the tests are disabled.)

**Comment by AdamWill** [comment]
"The CMake build script will automatically conduct the spell checking via that target if podspell/spell are installed. (If that's not the case a status message is logged during the configuration stating that the tests are disabled.)"

That seems reasonable to me. Thanks!

**Pull request closed without merging**
