### PR TITLE
Enhanced live

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
the HTML and javascript is not supposed to stay - but it's way easier to develop if you only need to restart one service

**Comment by coolo** [comment]
Now providing status to WS clients as it happens

**Comment by Martchus** [comment]
Actually the developer mode looks like a nice feature to me. Maybe you can make it stay but disable it by default?

**Comment by coolo** [comment]
For the time being sure, but the end goal is definitely to maintain this in openQA instead

**Comment by coolo** [comment]
superseded by #966

**Pull request closed without merging**
