### PR TITLE
backend::baseclass: Fix wording of informative message

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by baierjan** [comment]
Changes look good, apparently the wording is very important for one of our tests.

**Review by Martchus — APPROVED** [review]

**Review by foursixnine — APPROVED** [review]
Looks like you need to adjust the tests

**Comment by okurz** [comment]
> Looks like you need to adjust the tests

Fixed

**Comment by kalikiana** [comment]
7:     #   Failed test 'Existing SSH connection announced in logs'
7:     #   at ./t/23-baseclass.t line 229.
7:     # STDERR:
7:     # [2023-10-20 11:00:17.00000] [2504] [debug] <<< backend::baseclass::new_ssh_connection(keep_open=1, ***, hostname="foo.bar", username="root")
7:     # [2023-10-20 11:00:17.00000] [2504] [debug] Closing broken SSH connection (key:hostname=foo.bar,username=root,port=22)
7:     # [2023-10-20 11:00:17.00000] [2504] [debug] SSH connection to root@foo.bar established
7:     # 
7:     # doesn't match:
7:     # (?^u:Close broken SSH connection[\s\S]+SSH connection to root\@foo\.bar established)
7:     # as expected
7:     # Looks like you failed 1 test of 78.

**Pull request merged**
