### PR TITLE
git-subrepo update external/os-autoinst-common

### PR DESCRIPTION
**Pull request by perlpunk**
git subrepo clone (merge) --force git@github.com:os-autoinst/os-autoinst-common.git external/os-autoinst-common
    
    subrepo:
      subdir:   "external/os-autoinst-common"
      merged:   "6e38846c"
    upstream:
      origin:   "git@github.com:os-autoinst/os-autoinst-common.git"
      branch:   "master"
      commit:   "6e38846c"
    git-subrepo:
      version:  "0.4.6"
      origin:   "git@github.com:ingydotnet/git-subrepo"
      commit:   "110b9eb"

### CODE REVIEW

**Review by okurz — APPROVED** [review]
So the update is necessary but after the update we need to ensure everything still or again works.

**Review by Martchus — APPROVED** [review]

**Comment by perlpunk** [comment]
failing test: https://build.opensuse.org/package/live_build_log/devel:openQA:GitHub:os-autoinst:os-autoinst:PR-2443/os-autoinst/openSUSE_Tumbleweed/x86_64
```
[   40s] 3: [15:28:04] ./t/00-compile-check-all.t .............................. 
[   40s] 3: ok 1 - Syntax check autotest.pm
...
[   59s] 3: 
[   59s] 3: #   Failed test 'Syntax check external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm'
[   59s] 3: #   at /usr/lib/perl5/vendor_perl/5.38.0/Test/Strict.pm line 435.
[   59s] 3: # Can't locate Perl/Critic/Utils.pm in @INC (you may need to install the Perl::Critic::Utils module) (@INC entries checked: /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/lib /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/arch/auto/tinycv /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/site_perl /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl) at external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm line 11.
[   59s] 3: # BEGIN failed--compilation aborted at external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm line 11.
[   59s] 3: ok 248 - use strict   external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm
[   59s] 3: ok 249 - use warnings external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm
[   59s] 3: not ok 250 - Syntax check external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm
[   59s] 3: 
[   59s] 3: #   Failed test 'Syntax check external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm'
[   59s] 3: #   at /usr/lib/perl5/vendor_perl/5.38.0/Test/Strict.pm line 435.
[   59s] 3: # Can't locate Perl/Critic/Utils.pm in @INC (you may need to install the Perl::Critic::Utils module) (@INC entries checked: /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/lib /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/arch/auto/tinycv /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/site_perl /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl) at external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm line 11.
[   59s] 3: # BEGIN failed--compilation aborted at external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm line 11.
[   59s] 3: ok 251 - use strict   external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm
[   59s] 3: ok 252 - use warnings external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm
[   59s] 3: not ok 253 - Syntax check external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/RedundantStrictWarning.pm
[   59s] 3: 
[   59s] 3: #   Failed test 'Syntax check external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/RedundantStrictWarning.pm'
[   59s] 3: #   at /usr/lib/perl5/vendor_perl/5.38.0/Test/Strict.pm line 435.
[   59s] 3: # Base class package "Perl::Critic::Policy::TestingAndDebugging::RequireUseStrict" is empty.
[   59s] 3: #     (Perhaps you need to 'use' the module which defines that package first,
[   59s] 3: #     or make that module available in @INC (@INC contains: /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/lib /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/arch/auto/tinycv /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/site_perl /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl).
[   59s] 3: #  at external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/RedundantStrictWarning.pm line 11.
[   59s] 3: # BEGIN failed--compilation aborted at external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/RedundantStrictWarning.pm line 11.
[   59s] 3: ok 254 - use strict   external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/RedundantStrictWarning.pm
[   59s] 3: ok 255 - use warnings external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/RedundantStrictWarning.pm
[   59s] 3: ok 256 - Syntax check external/os-autoinst-common/tools/perlcritic
[   59s] 3: ok 257 - use strict   external/os-autoinst-common/tools/perlcritic
[   59s] 3: ok 258 - use warnings external/os-autoinst-common/tools/perlcritic
[   59s] 3: not ok 259 - Syntax check external/os-autoinst-common/tools/tidyall
[   59s] 3: 
[   59s] 3: #   Failed test 'Syntax check external/os-autoinst-common/tools/tidyall'
[   59s] 3: #   at /usr/lib/perl5/vendor_perl/5.38.0/Test/Strict.pm line 435.
[   59s] 3: # Can't locate Perl/Tidy.pm in @INC (you may need to install the Perl::Tidy module) (@INC entries checked: /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/lib /home/abuild/rpmbuild/BUILD/os-autoinst-4.6.1705591552.5ceed1a/ppmclibs/blib/arch/auto/tinycv /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/site_perl /usr/lib/perl5/site_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38.2 /usr/lib/perl5/vendor_perl/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.2 /usr/lib/perl5/5.38.2/x86_64-linux-thread-multi /usr/lib/perl5/5.38.2 /usr/lib/perl5/vendor_perl/5.38.0/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.38.0 /usr/lib/perl5/site_perl) at external/os-autoinst-common/tools/tidyall line 9.
[   59s] 3: # BEGIN failed--compilation aborted at external/os-autoinst-common/tools/tidyall line 9.
...
[   89s] 3: 1..537
[   89s] 3: # Looks like you failed 4 tests of 537.
[   89s] 3: Dubious, test returned 4 (wstat 1024, 0x400)
[   89s] 3: Failed 4/537 subtests 
```
@josegomezr

**Comment by perlpunk** [comment]
I managed to exclude files under external/ in the compile check; let's see if it passes now.

**Comment by perlpunk** [comment]
https://build.opensuse.org/package/live_build_log/devel:openQA:GitHub:os-autoinst:os-autoinst:PR-2443/os-autoinst/openSUSE_Tumbleweed/x86_64
```
[   36s] 1: external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/ArgumentInUseStrictWarnings.pm missing from installed files. Add to install instructions in CMakeLists.txt.
[   36s] 1/3 Test #1: test-installed-files .............***Failed    0.19 sec
```

**Comment by perlpunk** [comment]
new pr: #2444

**Pull request closed without merging**
