### PR TITLE
Prevent warning about uninitialized variable in script_run

### PR DESCRIPTION
**Pull request by okurz**
As observed in https://openqa.suse.de/tests/395751/file/autoinst-log.txt

### CODE REVIEW

**Comment by aaannz** [comment]
If script run produces uninit var warning then it is not called via testapi. Is that like, hmm, supported?

**Comment by aaannz** [comment]
Found it in `lib/susedistribution.pm` in tests. Funny that we sometimes use testapi, sometimes directly distribution object.

**Comment by coolo** [comment]
as testapi uses $distri using testapi doesn't make sense in some cases. actually testapi is just too fat, but splitting it now is a hard sell

**Comment by coolo** [comment]
I would prefer if you spell out the default for $wait instead of having a guard before every if

**Comment by aaannz** [comment]
> actually testapi is just too fat

True to that, esp. this `distribution.pm` and its derivatives backed stuff makes it harder to explain to new comers, esp. on conferences whit people outside SUSE background. Different topic however.

> I would prefer if you spell out the default for $wait instead of having a guard before every if

That is the preferred solution for me too. Just take it from testapi script_run:
```perl
$wait //= $bmwqemu::default_timeout;
```

**Comment by okurz** [comment]
updated:
* set default as necessary instead of if

**Pull request merged**
