### PR TITLE
Write the complete check result to the result file

### PR DESCRIPTION
**Pull request by nilxam**
In the old code, write a dummy needle to the result file in interactive mode seems wrong, it should write the complete check result from check_asserted_screen to the result file. Also moved $rsp->{saveresult}
part to the timeout block but just do not set overall state, $rsp->{timeout} must be 1 when $rsp->{saversult} was set to 1.

https://progress.opensuse.org/issues/13456

### CODE REVIEW

**Comment by nilxam** [comment]
Quick fix, the second test run is still running.

@AdamWill can you try it on your machine too?

**Comment by AdamWill** [comment]
OK, I've applied it to our staging instance. Seems to work in a quick test. Will update if any issues appear in more extended use.

**Comment by aaannz** [comment]
:+1:

**Comment by nilxam** [comment]
any problem not to merge it here?

**Comment by AdamWill** [comment]
still seems to be working fine here, I've done several needles in interactive mode fine, and not noticed any other negative effects.

**Pull request merged**
