### PR TITLE
Add tests for web socket route of command server

### PR DESCRIPTION
**Pull request by Martchus**

### CODE REVIEW

**Comment by Martchus** [comment]
The coverage is unaffected. So we already test the web socket server somewhere else?

**Comment by coolo** [comment]
I doubt it, I would rather assume that the extra report of command process is not working

**Comment by mudler** [comment]
you have to make the process call Devel::Report if it's a different process hitting that codepath. Or create unit tests directly targetting OpenQA::Commands

**Comment by Martchus** [comment]
@mudler Yes, but I thought the already present line `Devel::Cover::report() if Devel::Cover->can('report');` in `commands::start_server()` would do it. But apparently there's something missing.

**Comment by foursixnine** [comment]
@mudler Do you have any clue on why the code is shown as partially covered?. (Specially OpenQA::Commands, it does not show anywhere)

**Pull request merged**
