### PR TITLE
svirt: Wait for logfile from script in open_serial_console_via_ssh

### PR DESCRIPTION
**Pull request by cfconrad**
Because of commit cc0d5e79, we do not reconnect to a remote SSH command
with each `run_ssh_cmd()` call. This change the timing and cause a problem when
running `virsh console` in a `script` session, because the first
`type_string("\n")` command comes to early and gets discarded.

This workaround waits till `script` created the logfile, so we can
assume that STDIN and STDOUT is ready to be used.

Ticket: https://progress.opensuse.org/issues/60176
VR: http://fromm.arch.suse.de/tests/298 (incomplete because of a `Read-only file` error in _svirt_upload_assets_)

### CODE REVIEW

**Comment by okurz** [comment]
Looks reasonable. For the mentioned ticket please keep in mind that I still think the logic seems to be flawed – could also be related to the backend – because there are multiple, different checks for the login prompt, the bash prompt and login prompt again which only matches by accident. So I can merge this but the ticket would not be resolved without these additional steps going away.

**Comment by okurz** [comment]
could https://build.opensuse.org/package/live_build_log/devel:openQA/os-autoinst/openSUSE_Leap_15.1/aarch64 be related to this PR or your other recent changes? It says:

```
[  239s]     not ok 21 - Ensure run_ssh_cmd(keep_open => 0) uses a new SSH connection
[  239s]     #   Failed test 'Ensure run_ssh_cmd(keep_open => 0) uses a new SSH connection'
[  239s]     #   at ./22-svirt.t line 184.
[  239s]     #          got: '6'
[  239s]     #     expected: '5'
[  239s]     ok 22 - SSH connection 187651107898840 connected
[  239s]     ok 23 - SSH connection 187651107898840 connected
[  239s]     ok 24 - SSH connection 187651108113368 connected
[  239s] [2019-11-26T10:29:01.685 UTC] [debug] SSH disconnect hostname=bar,username=foo911
[  239s] [2019-11-26T10:29:01.685 UTC] [debug] SSH disconnect hostname=bar,username=root
[  239s]     ok 25 - Cleanup ssh connections
[  239s]     ok 26 - SSH connection 187651107898840 is disconnected
[  239s]     ok 27 - SSH connection 187651107898840 is disconnected
[  239s]     ok 28 - SSH connection 187651108113368 is disconnected
[  239s] [2019-11-26T10:29:01.688 UTC] [debug] <<< backend::baseclass::run_ssh_cmd(cmd='echo "BLAFAFU"', password='SECRET', wantarray=0, username=undef, hostname='hostname_svirt', keep_open=1)
[  239s] [2019-11-26T10:29:01.689 UTC] [debug] <<< backend::baseclass::run_ssh(cmd='echo "BLAFAFU"', hostname='hostname_svirt', keep_open=1, username=undef, wantarray=0, password='SECRET')
[  239s] [2019-11-26T10:29:01.689 UTC] [debug] <<< backend::baseclass::new_ssh_connection(keep_open=1, hostname='hostname_svirt', username=undef, password='SECRET', blocking=1, wantarray=0)
[  239s]     ok 29 - Correct username for ssh connection
[  239s]     ok 30 - Correct password for ssh connection
[  239s] [2019-11-26T10:29:01.691 UTC] [debug] SSH connection to root@hostname_svirt established
[  239s] [2019-11-26T10:29:01.698 UTC] [debug] [run_ssh_cmd(echo "BLAFAFU")] stdout:
[  239s] BLAFAFU
[  239s] 
[  239s] [2019-11-26T10:29:01.698 UTC] [debug] [run_ssh_cmd(echo "BLAFAFU")] exit-code: 0
[  239s]     ok 31 - sshVirtsh::run_cmd() test return value 
[  239s] [2019-11-26T10:29:01.700 UTC] [debug] <<< backend::baseclass::run_ssh_cmd(cmd='echo -n "BLAFAFU"', keep_open=1, hostname='hostname_svirt', username=undef, password='SECRET', wantarray=1)
[  239s] [2019-11-26T10:29:01.701 UTC] [debug] <<< backend::baseclass::run_ssh(cmd='echo -n "BLAFAFU"', password='SECRET', wantarray=1, username=undef, hostname='hostname_svirt', keep_open=1)
[  239s] [2019-11-26T10:29:01.701 UTC] [debug] <<< backend::baseclass::new_ssh_connection(blocking=1, wantarray=1, password='SECRET', keep_open=1, hostname='hostname_svirt', username=undef)
[  239s] [2019-11-26T10:29:01.708 UTC] [debug] [run_ssh_cmd(echo -n "BLAFAFU")] stdout:
[  239s] BLAFAFU
[  239s] [2019-11-26T10:29:01.708 UTC] [debug] [run_ssh_cmd(echo -n "BLAFAFU")] exit-code: 0
[  239s]     ok 32 - sshVirtsh::get_cmd_output()
[  239s] [2019-11-26T10:29:01.710 UTC] [debug] <<< backend::baseclass::run_ssh_cmd(cmd='echo -n "BLAFAFU"', hostname='hostname_svirt', keep_open=1, username=undef, password='SECRET', wantarray=1)
[  239s] [2019-11-26T10:29:01.711 UTC] [debug] <<< backend::baseclass::run_ssh(cmd='echo -n "BLAFAFU"', password='SECRET', wantarray=1, username=undef, keep_open=1, hostname='hostname_svirt')
[  239s] [2019-11-26T10:29:01.711 UTC] [debug] <<< backend::baseclass::new_ssh_connection(username=undef, keep_open=1, hostname='hostname_svirt', blocking=1, password='SECRET', wantarray=1)
[  239s] [2019-11-26T10:29:01.717 UTC] [debug] [run_ssh_cmd(echo -n "BLAFAFU")] stdout:
[  239s] BLAFAFU
[  239s] [2019-11-26T10:29:01.717 UTC] [debug] [run_ssh_cmd(echo -n "BLAFAFU")] exit-code: 0
[  239s]     ok 33 - sshVirtsh::get_cmd_output(wantarray => 1) 
[  239s]     1..33
[  239s]     # Looks like you failed 1 test of 33.
[  239s] not ok 6 - SSH usage in svirt
[  239s] #   Failed test 'SSH usage in svirt'
[  239s] #   at ./22-svirt.t line 204.
[  239s] ok 7 - no (unexpected) warnings (via done_testing)
[  239s] 1..7
[  239s] # Looks like you failed 1 test of 7.
[  239s] FAIL 22-svirt.t (exit status: 1)
[  239s] 
```

**Comment by cfconrad** [comment]
Hi @okurz, thx for pointing me.
But currently I have no glue where it comes from. We only check the [number](https://github.com/os-autoinst/os-autoinst/blob/master/t/22-svirt.t#L184) of "fake" ssh object here and each object is a key entry inside of `$ssh_obj_data`. This hash is propagated by mocking [connect](https://github.com/os-autoinst/os-autoinst/blob/master/t/22-svirt.t#L109) of `Net::SSH2`. 
The output of that test shows also only once the message `SSH connection to root@bar established`. Which indicates for me that we do call connect only once.

```
[  239s] [2019-11-26T10:29:01.671 UTC] [debug] <<< backend::baseclass::run_ssh_cmd(cmd='echo -n "foo"', keep_open=0, wantarray=0, password='SECRET')
[  239s] [2019-11-26T10:29:01.672 UTC] [debug] <<< backend::baseclass::run_ssh(cmd='echo -n "foo"', password='SECRET', wantarray=0, keep_open=0)
[  239s] [2019-11-26T10:29:01.672 UTC] [debug] <<< backend::baseclass::new_ssh_connection(password='SECRET', wantarray=0, blocking=1, keep_open=0)
[  239s]     ok 19 - Correct username for ssh connection
[  239s]     ok 20 - Correct password for ssh connection
[  239s] [2019-11-26T10:29:01.674 UTC] [debug] SSH connection to root@bar established
[  239s] [2019-11-26T10:29:01.680 UTC] [debug] [run_ssh_cmd(echo -n "foo")] stdout:
[  239s] foo
[  239s] [2019-11-26T10:29:01.680 UTC] [debug] [run_ssh_cmd(echo -n "foo")] exit-code: 0
```

And I don't understand why this test pass for `x86_64` but not for `aarch64 `.

**Comment by pevik** [comment]
> Looks reasonable. For the mentioned ticket please keep in mind that I still think the logic seems to be flawed – could also be related to the backend – because there are multiple, different checks for the login prompt, the bash prompt and login prompt again which only matches by accident. So I can merge this but the ticket would not be resolved without these additional steps going away.

I'll reacted to this at the ticket https://progress.opensuse.org/issues/60176#note-17

**Pull request merged**
