### PR TITLE
WIP Tests & Coverage

### PR DESCRIPTION
**Pull request by perlpunk**
Run tests with `prove` from top directory.
This seems to report coverage of more files. The overall coverage is decreasing, but it might be closer to the truth than what we currently have ;-)

### CODE REVIEW

**Comment by okurz** [comment]
In general I like it. I also wanted to make tests rely less on autotools and just prove.

**Comment by perlpunk** [comment]
There's still something wrong with the reported coverage.
I can see code executed locally when adding debugging, but still Devel::Cover says it's not.

I can't even explain why those 27 new files appear in the coverage, and why they didn't before. Maybe it has to do with the current working directory changing one level up.
Will do more research.

**Comment by okurz** [comment]
I guess we can finally see all the ugly warnings and output in the tests which are not hidden anymore :)

There seem to be some tests which are producing non-deterministic coverage, e.g. for "OpenQA/Benchmark/Stopwatch.pm" which commonly reports 71.6% stmt coverage or 100% as in your latest travis CI test run https://travis-ci.org/os-autoinst/os-autoinst/builds/619136255#L1501

Mainly files report higher coverage than what I am used to, but for example https://travis-ci.org/os-autoinst/os-autoinst/builds/619136255#L1507 shows just 41% for Utils.pm which I have seen with 100%. https://travis-ci.org/os-autoinst/os-autoinst/builds/619136255#L1520 shows 32% for autotest vs. 51% . The main application "isotovideo" is not mentioned at all. Seems your tests have lost this part which can probably also explain the other big losses. It looks like e.g. the fullstack test is executed but probably coverage from spawned processes not taken into account.

**Comment by perlpunk** [comment]
`Coverage   41.44%   42.42%   +0.97%`
Now adding Devel::Cover back in 07-commands.t

**Comment by perlpunk** [comment]
So we have over 5% more coverage (with keeping Devel::Cover in 07-commands.t), but still backend::driver has a loss of 67%.
Need to find out which test should be covering the missing code and compare master and PR in detail.

**Comment by perlpunk** [comment]
Just removed Devel::Cover from 07-commands.t again and still got
`Coverage   41.44%   46.71%   +5.26%`
So it seems to be random.

**Pull request closed without merging**
