### PR TITLE
send_key_until_needlematch: Avoid check_screen timeout in the first iteration

### PR DESCRIPTION
**Pull request by Vogtinator**
When send_key_until_needlematch is called, the key was not pressed yet, so
the expected state is either already there or won't automatically appear,
so don't waste time waiting for it. Instead press the key immediately if
check_screen fails.

VR: http://10.168.4.168/tests/1232

### CODE REVIEW

**Comment by Vogtinator** [comment]
> However I would be fine to merge this if you could add test coverage for the function, e.g. in t/03-testapi.t,

I'll try that if it's not too involved, but I don't really understand why this is a requirement. Having a unit test doesn't really offset the potential that it might break some use of the function, does it?

> plus bump the version number in OpenQA/Isotovideo/Interface.pm

Is that really necessary? The behaviour doesn't really change in a meaningful way and the API remains completely unchanged.

**Comment by okurz** [comment]
> > However I would be fine to merge this if you could add test coverage for the function, e.g. in t/03-testapi.t,
> 
> I'll try that if it's not too involved, but I don't really understand why this is a requirement. Having a unit test doesn't really offset the potential that it might break some use of the function, does it?

Are you arguing with Edsger W. Dijkstra “Program testing can be used to show the presence of bugs, but never to show their absence!”?

> > plus bump the version number in OpenQA/Isotovideo/Interface.pm
> 
> Is that really necessary? The behaviour doesn't really change in a meaningful way and the API remains completely unchanged.

But it *does* chance, just bump it, it's just a number :)

**Comment by Vogtinator** [comment]
> > > However I would be fine to merge this if you could add test coverage for the function, e.g. in t/03-testapi.t,
> > 
> > 
> > I'll try that if it's not too involved, but I don't really understand why this is a requirement. Having a unit test doesn't really offset the potential that it might break some use of the function, does it?
> 
> Are you arguing with Edsger W. Dijkstra “Program testing can be used to show the presence of bugs, but never to show their absence!”?

Not necessarily. I'll try the argument one step further: If this change proves to be somehow worse than before (which I doubt), then writing a unittest for this would be a waste of time. From that PoV, it would actually make sense to apply the change first, wait a bit and only then add a test! Otherwise we'd test that the suboptimal behaviour is present...

> > > plus bump the version number in OpenQA/Isotovideo/Interface.pm
> > 
> > 
> > Is that really necessary? The behaviour doesn't really change in a meaningful way and the API remains completely unchanged.
> 
> But it _does_ chance, just bump it, it's just a number :)

Sure, just wondering.

**Comment by Vogtinator** [comment]
Here's an attempt I spent way too much time on: https://github.com/Vogtinator/os-autoinst/tree/broken-useless-unit-test. I won't waste another millisecond on that, but feel free to continue on your own.

The test is orders of magnitude more fragile and prone to break than the method it's supposed to test. Given the simple logic in the method here, I'm now of the opinion that there shouldn't be a unit test for it at all.

**Comment by okurz** [comment]
> Not necessarily. I'll try the argument one step further: If this change proves to be somehow worse than before (which I doubt), then writing a unittest for this would be a waste of time. From that PoV, it would actually make sense to apply the change first, wait a bit and only then add a test! Otherwise we'd test that the suboptimal behaviour is present...

Yes, tests prove that the current behaviour work as expected, not that it's optimal. I would say you don't need to come up with perfect tests covering the exact behaviour, at least just have some reasonable code that executes the touched code path, i.e. complete statement coverage.

**Comment by Vogtinator** [comment]
> > Not necessarily. I'll try the argument one step further: If this change proves to be somehow worse than before (which I doubt), then writing a unittest for this would be a waste of time. From that PoV, it would actually make sense to apply the change first, wait a bit and only then add a test! Otherwise we'd test that the suboptimal behaviour is present...
> 
> Yes, tests prove that the current behaviour work as expected, not that it's optimal. I would say you don't need to come up with perfect tests covering the exact behaviour, at least just have some reasonable code that executes the touched code path, i.e. complete statement coverage.

Did you check the code in the branch I linked?

While originally I thought this would only improve performance, this might also improve https://progress.opensuse.org/issues/113447, e.g. https://openqa.opensuse.org/tests/2473779#step/bootloader_uefi/11.

**Comment by Vogtinator** [comment]
> > > > Not necessarily. I'll try the argument one step further: If this change proves to be somehow worse than before (which I doubt), then writing a unittest for this would be a waste of time. From that PoV, it would actually make sense to apply the change first, wait a bit and only then add a test! Otherwise we'd test that the suboptimal behaviour is present...
> > > 
> > > 
> > > Yes, tests prove that the current behaviour work as expected, not that it's optimal. I would say you don't need to come up with perfect tests covering the exact behaviour, at least just have some reasonable code that executes the touched code path, i.e. complete statement coverage.
> > 
> > 
> > Did you check the code in the branch I linked?
> 
> I did. Not sure what you want me to tell you.

Whether it's on the "right track" or if not, what is wrong.

> > While originally I thought this would only improve performance, this might also improve https://progress.opensuse.org/issues/113447, e.g. https://openqa.opensuse.org/tests/2473779#step/bootloader_uefi/11.
> 
> Good point. Yes, can very well happen in such cases as well.

**Comment by okurz** [comment]
> > > > > Not necessarily. I'll try the argument one step further: If this change proves to be somehow worse than before (which I doubt), then writing a unittest for this would be a waste of time. From that PoV, it would actually make sense to apply the change first, wait a bit and only then add a test! Otherwise we'd test that the suboptimal behaviour is present...
> > > > 
> > > > 
> > > > Yes, tests prove that the current behaviour work as expected, not that it's optimal. I would say you don't need to come up with perfect tests covering the exact behaviour, at least just have some reasonable code that executes the touched code path, i.e. complete statement coverage.
> > > 
> > > 
> > > Did you check the code in the branch I linked?
> > 
> > 
> > I did. Not sure what you want me to tell you.
> 
> Whether it's on the "right track" or if not, what is wrong.

To me
https://github.com/os-autoinst/os-autoinst/commit/17bd7a5094cd96d24b7b85b41a520bcfcc33625b
looks completely fine. I would go with it.

**Comment by Vogtinator** [comment]
> To me [17bd7a5](https://github.com/os-autoinst/os-autoinst/commit/17bd7a5094cd96d24b7b85b41a520bcfcc33625b) looks completely fine. I would go with it.

Ok, done.

**Review by kalikiana — APPROVED** [review]

**Review by okurz — CHANGES_REQUESTED** [review]
Ok, please also just bump the API version number, rest is fine

**Comment by Vogtinator** [comment]
Ping. I'd like to see whether this improves the annoying issue with `bootloader_uefi` fails on aarch64.

**Review by Martchus — APPROVED** [review]

**Comment by Vogtinator** [comment]
First fallout! https://openqa.opensuse.org/tests/2507164

I'll make a PR to address that.

**Comment by Vogtinator** [comment]
> First fallout! https://openqa.opensuse.org/tests/2507164
> 
> I'll make a PR to address that.

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15347

**Comment by DimStar77** [comment]
This also seems to be a fallout from here:
https://openqa.opensuse.org/tests/2507350#step/boot_into_snapshot/53

**Comment by Vogtinator** [comment]
> This also seems to be a fallout from here: https://openqa.opensuse.org/tests/2507350#step/boot_into_snapshot/53

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15358

**Comment by dzedro** [comment]
Another few https://openqa.suse.de/tests/9308870#step/change_desktop/17
https://openqa.suse.de/tests/9315850#step/grub2_test/80

**Comment by Vogtinator** [comment]
> Another few https://openqa.suse.de/tests/9308870#step/change_desktop/17 https://openqa.suse.de/tests/9315850#step/grub2_test/80

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15361

**Comment by bs-suse** [comment]
I've not checked if similar ones are already mentioned above, but these are the ones that let me stumble about this:
https://openqa.suse.de/tests/9339832#step/releasenotes/13
https://openqa.suse.de/tests/9339836#step/releasenotes/13
https://openqa.suse.de/tests/9339396#step/releasenotes/13
https://openqa.suse.de/tests/9339400#step/releasenotes/13

**Comment by Vogtinator** [comment]
> I've not checked if similar ones are already mentioned above, but these are the ones that let me stumble about this: https://openqa.suse.de/tests/9339832#step/releasenotes/13 https://openqa.suse.de/tests/9339836#step/releasenotes/13 https://openqa.suse.de/tests/9339396#step/releasenotes/13 https://openqa.suse.de/tests/9339400#step/releasenotes/13

The code is already prepared to handle this, but it's disabled in textmode for some reason:

```
         if (!check_var('VIDEOMODE', 'text')) {
             # Make sure release notes window is shown to avoid sending key too early
             # It takes longer time to show multilple release notes for addons
             assert_screen([qw(release-notes-sle-ok-button release-notes-sle-close-button)], 300);
         }
```

I suggest to just drop the condition.

**Pull request merged**
