### PR TITLE
Add option to upload assets on demand even in failed jobs

### PR DESCRIPTION
**Pull request by okurz**
Example log output:

```
[Sat Dec 16 08:20:34 2017] [18363:debug] >>> testapi::_check_backend_response: match=bootloader timed out after 30
[Sat Dec 16 08:20:35 2017] [18363:debug] test boot failed
[Sat Dec 16 08:20:35 2017] [18357:debug] isotovideo done
[Sat Dec 16 08:20:35 2017] [18357:debug] BACKEND SHUTDOWN
[Sat Dec 16 08:20:36 2017] [18368:debug] sending magic and exit
[Sat Dec 16 08:20:36 2017] [18357:debug] received magic close
[Sat Dec 16 08:20:36 2017] [18357:debug] preparing hdd 1 for upload as opensuse-Tumbleweed-x86_64-20170505-textmode@64bit.qcow2 in qcow2
[Sat Dec 16 08:20:36 2017] [18357:debug] running nice ionice qemu-img convert -O qcow2 raid/l1 assets_public/opensuse-Tumbleweed-x86_64-20170505-textmode@64bit.qcow
```

### CODE REVIEW

**Comment by coolo** [comment]
I have my doubts that this works. Because if the test suite is not complete, the vm is most likely not shutdown.

**Comment by okurz** [comment]
This is why in this case I do not check for the VM to be shutdown. It might not work in all cases but in more than none :) I did the check that you can see above where it kind of worked. At least it really uploaded a qcow file.

**Comment by coolo** [comment]
but boot in this case was fatal? Because non-fatal failures are rolled back - and publishing the hdd for debugging purposes as such worthless.

**Comment by okurz** [comment]
Depends on the milestone and what the investigator actually wants to debug, e.g. If it's not the last failing module but often just the installed system with all the packages,  versions,  patterns etc.

**Comment by coolo** [comment]
I still would opt to extend the usability of this feature - and make all tests fatal, so they end up uploading their failed status - and as we can't shutdown the VM, but you have to save *something* - we could save a snapshot 'lastfail'. So that you can 'boot' the VM with -loadvm 'lastfail'.

**Comment by okurz** [comment]
Well, sounds useful. Well take me [some_time:eternity[ though ;)

**Comment by foursixnine** [comment]
@coolo I take that you still would like this?

**Comment by coolo** [comment]
the story is different after @richiejp's changes. So it needs to be reevaluated from scratch :)

**Comment by Martchus** [comment]
So it likely doesn't even make sense to rebase this branch. Should we close it to keep the list of open PR shorter?

**Comment by okurz** [comment]
I thought it made sense to rebase. Please take a look again in the current updated state if you like it better. I also added an automatic test.

**Comment by okurz** [comment]
Hm, the tests fail to execute because qemu is called in 14-isotovideo and kvm is not available. How do we handle that for the full stack test?

**Comment by Martchus** [comment]
We set the test variable `QEMU_NO_KVM` to `1`.

**Comment by okurz** [comment]
all set. Ready to merge?

**Comment by Martchus** [comment]
Since @coolo had initially some objections I leave clicking the merge button to him.

**Pull request merged**
