### PR TITLE
Add watchdog to sanity check timing

### PR DESCRIPTION
**Pull request by coolo**
If it takes longer than 2 seconds to write a screenshot, our
assumptions about timing in tests is screwed, so make sure
the worker is able to handle that

### CODE REVIEW

**Comment by coolo** [comment]
This PR is mainly to document the code I'm deploying on our workers - we need to define a sane limit. I'm unable to proceed a test with this limit on my workstation, so it's probably too strict.

**Comment by coolo** [comment]
so as I expected, 90% of the tests fail now. The highscore for a single capture_screenshot is 33.4s

**Comment by coolo** [comment]
I now added warnings for slow needle matching and slow capture_screenshot - and upped the limit to die for to 10 * screenshot_interval (which is 5s)

**Comment by coolo** [comment]
I think it's a good thing to have - so I removed the tag

**Comment by aaannz** [comment]
:+1:

**Pull request merged**
