### PR TITLE
[WIP] Add test API call 'set_typing_speed'

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/18200

### CODE REVIEW

**Comment by coolo** [comment]
I would think we better go with a generic backend_reload_vars command - and leave it to the testapi to save it first

**Comment by coolo** [comment]
... because that can also be useful if switching scenarios

**Comment by okurz** [comment]
and then you don't want the explicit set_typing_speed additionally?

**Comment by coolo** [comment]
right. set_var would trigger a backend_reload - and we would have to make sure not to use set_var in backend :)

**Comment by asmorodskyi** [comment]
poo#18200 marked as resolved is this PR is still relevant ?

**Comment by okurz** [comment]
it serves as a reminder that we would like to have a backend command for saving/loading the variables covering all threads but I will close this PR.

**Pull request closed without merging**
