### PR TITLE
Remove deprecated backends after one-year notice

### PR DESCRIPTION
**Pull request by okurz**
The backends 'ikvm' and 'pvm' have been marked as deprecated since
cb487f2c which is now one year past. As we have not received any message
about users still needing this backend we can now remove the
corresponding files.

Related progress issue: https://progress.opensuse.org/issues/109740

### CODE REVIEW

**Comment by okurz** [comment]
Added "not-ready" label to keep this open for at least 2 weeks of notice period.

**Review by perlpunk — COMMENTED** [review]
CMakeLists.txt also needs to be updated

**Comment by okurz** [comment]
@mergifyio rebase

**Comment by okurz** [comment]
I don't understand why the coverage check fails. I checked https://app.codecov.io/gh/os-autoinst/os-autoinst/pull/2260/tree for all paths of "fully_covered" and they are all at 100%. Should we merge regardless and check in follow-up PRs how it behaves?

**Comment by Martchus** [comment]
Maybe removing the files and removing the ignore-config for them is too much in one step. However, I suppose we can nevertheless merge it because it'll likely be fine again on the next PR.

**Comment by kalikiana** [comment]
@Mergifyio rebase

**Comment by okurz** [comment]
> Maybe removing the files and removing the ignore-config for them is too much in one step. However, I suppose we can nevertheless merge it because it'll likely be fine again on the next PR.

ok, I will do that now.

**Review by mimi1vx — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Review by baierjan — APPROVED** [review]

**Pull request merged**
