### PR TITLE
Make zKVM capable of variable CPU and RAM

### PR DESCRIPTION
**Pull request by Soulofdestiny**
For some tests we need more RAM and vCPUs on z/KVM

### CODE REVIEW

**Comment by coolo** [comment]
please document in docs/backend_vars that QEMU variables affect the svirt backend

**Comment by Soulofdestiny** [comment]
done

**Comment by coolo** [comment]
@mnowaksuse WDYT?

**Comment by mnowaksuse** [comment]
Looks fine with me as we may need to craft RAM size for VMware anyway, because it's "memory size has to be a multiple of 4096", once we get there.

**Comment by Soulofdestiny** [comment]
this is apparently not working correctly, e.g. the xml-parameters are not set
https://openqa.suse.de/tests/358287

when i check the xml file after the system was defined, it hast still default values in it

**Comment by Soulofdestiny** [comment]
mhm... works on local instance - it's not deployed yet in productive?

**Comment by coolo** [comment]
we have 3492b1 deployed

**Pull request merged**
