### PR TITLE
Make 07-commands.t callable by prove

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
anyone has an idea how `t/07-commands.t` can be changed to be callable by prove?

**Comment by okurz** [comment]
@coolo can you help me with that? I tried do make the tests compatible with `prove` but failed with t/07-commands.t. It hangs when executing with `prove t/07-commands.t`.

**Comment by coolo** [comment]
http://paste.opensuse.org/41614718

**Comment by coolo** [comment]
execute summary: kill($pid) does not what it does in C - and prove waits for subprocesses to finish

**Comment by okurz** [comment]
thx, fixed and updated.

**Comment by coolo** [comment]
So now it fails due to https://github.com/os-autoinst/os-autoinst/issues/602

**Comment by okurz** [comment]
but works locally. As long as we don't introduce a call to "prove" in make we should be good and @kraih will fix #602 asap, right?

**Comment by coolo** [comment]
merged into #618

**Pull request closed without merging**
