### PR TITLE
[needs testing] Add serial support for IPMI

### PR DESCRIPTION
**Pull request by asdil12**
This patch is not yet tested.

### CODE REVIEW

**Comment by coolo** [comment]
doesn't work

**Comment by asdil12** [comment]
This seems to work (as far as I can test - that means that I can at least see the BIOS messages in the serial0 file).

**Comment by asdil12** [comment]
@coolo Could you give it a try and merge if it is ok?

**Comment by coolo** [comment]
I gave it a try and the serial0 file indeed contains useful stuff. but it also contains so many 0 bytes that it's basically useless ;(

I guess we need some kind of post processing

**Comment by coolo** [comment]
rebased and pushed to master

**Pull request closed without merging**
