### PR TITLE
Filter out carriage returns

### PR DESCRIPTION
**Pull request by mloviska**
Jobs running on hyperv or vmware usually contain LF and CR.
In our particular case `0d  0d  0a` seems to be present in each line of
SUTs output.

Received string from hyperv job:

```
 $VAR1 = 'n1~0x

NAME="SLES"

VERSION="15-SP3 Beta2"

VERSION_ID="15.3"

PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3 (Beta2)"

ID="sles"

ID_LIKE="suse"

ANSI_COLOR="0;32"

CPE_NAME="cpe:/o:suse:sles:15:sp3"

DOCUMENT_URL="https://documentation.suse.com/"

SCRIPT_FINISHEDn1~0x-0-

';
```
Ouput in hex:

```
$VAR1 = ' 6e  31  7e  30  78  0d  0d  0a  4e  41  4d  45  3d  22  53  4c  45  53  22  0d  0d  0a  56  45  52  53  49  4f  4e  3d  22  31  35  2d  53  50  33  20  42  65  74  61  32  22  0d  0d  0a  56  45  52  53  49  4f  4e  5f  49  44  3d  22  31  35  2e  33  22  0d  0d  0a  50  52  45  54  54  59  5f  4e  41  4d  45  3d  22  53  55  53  45  20  4c  69  6e  75  78  20  45  6e  74  65  72  70  72  69  73  65  20  53  65  72  76  65  72  20  31  35  20  53  50  33  20  28  42  65  74  61  32  29  22  0d  0d  0a  49  44  3d  22  73  6c  65  73  22  0d  0d  0a  49  44  5f  4c  49  4b  45  3d  22  73  75  73  65  22  0d  0d  0a  41  4e  53  49  5f  43  4f  4c  4f  52  3d  22  30  3b  33  32  22  0d  0d  0a  43  50  45  5f  4e  41  4d  45  3d  22  63  70  65  3a  2f  6f  3a  73  75  73  65  3a  73  6c  65  73  3a  31  35  3a  73  70  33  22  0d  0d  0a  44  4f  43  55  4d  45  4e  54  5f  55  52  4c  3d  22  68  74  74  70  73  3a  2f  2f  64  6f  63  75  6d  65  6e  74  61  74  69  6f  6e  2e  73  75  73  65  2e  63  6f  6d  2f  22  0d  0d  0a  53  43  52  49  50  54  5f  46  49  4e  49  53  48  45  44  6e  31  7e  30  78  2d  30  2d  0d  0d  0a ';
```

After filtering:

```
$VAR1 = 'n1~0x
NAME="SLES"
VERSION="15-SP3 Beta2"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3 (Beta2)"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENT_URL="https://documentation.suse.com/"
SCRIPT_FINISHEDn1~0x-0-
';
```

```
$VAR1 = ' 6e  31  7e  30  78  0a  4e  41  4d  45  3d  22  53  4c  45  53  22  0a  56  45  52  53  49  4f  4e  3d  22  31  35  2d  53  50  33  20  42  65  74  61  32  22  0a  56  45  52  53  49  4f  4e  5f  49  44  3d  22  31  35  2e  33  22  0a  50  52  45  54  54  59  5f  4e  41  4d  45  3d  22  53  55  53  45  20  4c  69  6e  75  78  20  45  6e  74  65  72  70  72  69  73  65  20  53  65  72  76  65  72  20  31  35  20  53  50  33  20  28  42  65  74  61  32  29  22  0a  49  44  3d  22  73  6c  65  73  22  0a  49  44  5f  4c  49  4b  45  3d  22  73  75  73  65  22  0a  41  4e  53  49  5f  43  4f  4c  4f  52  3d  22  30  3b  33  32  22  0a  43  50  45  5f  4e  41  4d  45  3d  22  63  70  65  3a  2f  6f  3a  73  75  73  65  3a  73  6c  65  73  3a  31  35  3a  73  70  33  22  0a  44  4f  43  55  4d  45  4e  54  5f  55  52  4c  3d  22  68  74  74  70  73  3a  2f  2f  64  6f  63  75  6d  65  6e  74  61  74  69  6f  6e  2e  73  75  73  65  2e  63  6f  6d  2f  22  0a  53  43  52  49  50  54  5f  46  49  4e  49  53  48  45  44  6e  31  7e  30  78  2d  30  2d  0a ';
```

### CODE REVIEW

**Comment by mloviska** [comment]
VRs:

* [Build20.160-jeos-container-engines_and_tools@uefi-virtio-vga](http://kepler.suse.cz/tests/2866)
* [Build20.160-jeos-container-engines_and_tools@svirt-vmware65](http://kepler.suse.cz/tests/2867)
* [Build20.160-jeos-container-engines_and_tools@svirt-hyperv-uefi](http://kepler.suse.cz/tests/2868)

**Review by okurz — CHANGES_REQUESTED** [review]
Changing the public test API should not be taken lightly. Even if it seems trivial we should consider bumping the test API version, see https://github.com/os-autoinst/os-autoinst/blob/master/OpenQA/Isotovideo/Interface.pm#L25

Also please consider test additions or adaptions in t03-testapi.t

**Comment by Vogtinator** [comment]
That sounds like the `\n` -> `\r\n` substitution is done twice somewhere, resulting in `\r\r\n`. Can you check at which point(s) it does that?

**Comment by mloviska** [comment]
> That sounds like the `\n` -> `\r\n` substitution is done twice somewhere, resulting in `\r\r\n`. Can you check at which point(s) it does that?

Yup, good catch. I am trying to find where it comes from

**Comment by mloviska** [comment]
> Changing the public test API should not be taken lightly. Even if it seems trivial we should consider bumping the test API version, see https://github.com/os-autoinst/os-autoinst/blob/master/OpenQA/Isotovideo/Interface.pm#L25
> 
> Also please consider test additions or adaptions in t03-testapi.t

**Comment by mloviska** [comment]
> That sounds like the `\n` -> `\r\n` substitution is done twice somewhere, resulting in `\r\r\n`. Can you check at which point(s) it does that?

I haven't found any code reference but `s/nc/socat` might be our solution.

VRs:

* [Build20.160-jeos-container-engines_and_tools@uefi-virtio-vga](http://kepler.suse.cz/tests/2915)
* [jeos-container-engines_and_tools@svirt-hyperv-uefi](http://kepler.suse.cz/tests/2914)
* [jeos-container-engines_and_tools@svirt-vmware65](http://kepler.suse.cz/tests/2913)

**Comment by mloviska** [comment]
> Changing the public test API should not be taken lightly. Even if it seems trivial we should consider bumping the test API version, see https://github.com/os-autoinst/os-autoinst/blob/master/OpenQA/Isotovideo/Interface.pm#L25
> 
> Also please consider test additions or adaptions in t03-testapi.t

I have just replaced `netcat` for `socat`. Is really necessary to do version bump ?

**Comment by Vogtinator** [comment]
I guess the serial ports connected to use the telnet protocol? Apparently that demands use of CRLF for line termination.

`socat` has this in the man page: `Note: socat simply strips all CR characters.` That seems a bit excessive, but if it works for `socat`, it's probably also safe for us. Is the conversion in `testapi.pm` still needed?

**Comment by mloviska** [comment]
> `socat` has this in the man page: `Note: socat simply strips all CR characters.` That seems a bit excessive, but if it works for `socat`, it's probably also safe for us. Is the conversion in `testapi.pm` still needed?

I have understood it as the default behavior of `socat`, however using `socat - TCP4:openqaw7-hyperv.qa.suse.de:10008`
yield same results as using `nc`. 

http://kepler.suse.cz/tests/2897/file/serial0.txt

http://kepler.suse.cz/tests/2897/file/autoinst-log.txt

```

NAME="SLES"

VERSION="15-SP3 Beta2"

VERSION_ID="15.3"

PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3 (Beta2)"

ID="sles"

ID_LIKE="suse"

ANSI_COLOR="0;32"

CPE_NAME="cpe:/o:suse:sles:15:sp3"

DOCUMENT_URL="https://documentation.suse.com/"

SCRIPT_FINISHEDn1~0x-0-

TEST1_before $VAR1 = 'n1~0x

NAME="SLES"

VERSION="15-SP3 Beta2"

VERSION_ID="15.3"

PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3 (Beta2)"

ID="sles"

ID_LIKE="suse"

ANSI_COLOR="0;32"

CPE_NAME="cpe:/o:suse:sles:15:sp3"

DOCUMENT_URL="https://documentation.suse.com/"

SCRIPT_FINISHEDn1~0x-0-

';
TEST1_before_hex $VAR1 = '6e317e30780d0d0a4e414d453d22534c4553220d0d0a56455253494f4e3d2231352d535033204265746132220d0d0a56455253494f4e5f49443d2231352e33220d0d0a5052455454595f4e414d453d2253555345204c696e757820456e746572707269736520536572766572203135205350332028426574613229220d0d0a49443d22736c6573220d0d0a49445f4c494b453d2273757365220d0d0a414e53495f434f4c4f523d22303b3332220d0d0a4350455f4e414d453d226370653a2f6f3a737573653a736c65733a31353a737033220d0d0a444f43554d454e545f55524c3d2268747470733a2f2f646f63756d656e746174696f6e2e737573652e636f6d2f220d0d0a5343524950545f46494e49534845446e317e30782d302d0d0d0a';
```

So without `crnl` CRs are not stripped, or at least the additional one infront of `0d0a`. And as long as there is `crnl`, the conversion is still handy.

**Comment by Vogtinator** [comment]
> So without crnl CRs are not stripped, or at least the additional one infront of 0d0a. And as long as there is crnl, the conversion is still handy.

Yep, that option is the important part here. I don't think netcat or telnet offer something like that.

**Review by okurz — APPROVED** [review]
> […]
> I have just replaced `netcat` for `socat`. Is really necessary to do version bump ?

as you are not changing testapi itself anymore it's ok if you don't change the API version :)

**Comment by mloviska** [comment]
> > […]
> > I have just replaced `netcat` for `socat`. Is really necessary to do version bump ?
> 
> as you are not changing testapi itself anymore it's ok if you don't change the API version :)

Thanks!

**Comment by Vogtinator** [comment]
`dist/rpm/os-autoinst.spec` needs to pull in `socat` now, it might not be installed by default.

**Comment by mloviska** [comment]
> `dist/rpm/os-autoinst.spec` needs to pull in `socat` now, it might not be installed by default.

I have used o.s.d workers, and it was enough to install `socat` manually in `openQA_hyperv_intermediary` VM. I have done nothing in VMware though. Nevertheless, it sounds useful to me.

**Pull request merged**
