### PR TITLE
Correctly use QEMU_COMPRESS_QCOW2

### PR DESCRIPTION
**Pull request by mimi1vx**
commit https://github.com/os-autoinst/os-autoinst/commit/eb207de0a372d832a60a081dd08dc674c90ef950
missed part of needed changes to fully support this backend variable

### CODE REVIEW

**Review by okurz — APPROVED** [review]

**Comment by okurz** [comment]
Would be great if this fixes https://progress.opensuse.org/issues/99246 . Maybe you can verify this to be working also in production?

**Review by Martchus — APPROVED** [review]

**Comment by mimi1vx** [comment]
now running local testsuite , and preparing test in quasar to check how it works

**Review by okurz — APPROVED** [review]
Verified locally with

```
prove -I. t/*qemu*
t/12-bmwqemu.t ....... ok   
t/18-backend-qemu.t .. ok    
t/18-qemu-options.t .. ok   
t/18-qemu.t .......... ok    
All tests successful.
Files=4, Tests=70, 19 wallclock secs ( 0.12 usr  0.01 sys + 15.65 cusr 10.40 csys = 26.18 CPU)
Result: PASS
```

**Comment by okurz** [comment]
We will go ahead but you can still verify on other machines in parallel.

**Comment by mimi1vx** [comment]
http://quasar.suse.cz/tests/7200

**Comment by mimi1vx** [comment]
on other side name of this variable is misleading, only purpose is to disable compression :D

**Pull request merged**
