### PR TITLE
Add support for serial device of s390x in testapi

### PR DESCRIPTION
**Pull request by LKHN**
Use `/dev/ttysclp0` as a serial device for s390x architecture

### CODE REVIEW

**Review by Martchus — CHANGES_REQUESTED** [review]
I couldn't tell whether that would impact our s390x tests for SUSE. That's supposedly something we need to test. Or you further constrain this to be only used with the QEMU backend.

**Comment by Martchus** [comment]
You also need to adapt unit tests.

**Comment by LKHN** [comment]
@Martchus Thanks for the review!

Unfortunately, I don't have any other hardware to test it other backends. So I constrained this to be only used with the QEMU backend. 

The unit test also added.

**Review by Martchus — APPROVED** [review]

**Comment by Martchus** [comment]
Oh, I suppose it was you I have just declined a private chat via Matrix. If you still have questions we can chat via Matrix. I would also generally allow a private chat. However, it makes generally more sense to use the openQA room (#openqa:opensuse.org).

**Comment by LKHN** [comment]
Yes, It was me. Okay, I will do. thanks!

**Pull request merged**
