### PR TITLE
Expect fail with wait_serial

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by aaannz** [comment]
I'm confused. Isn't this something expect_not_found should handle? Do you have an example?

**Comment by aaannz** [comment]
Ah, didn't notice link to the test. However I think this is indeed covered by expect_not_found. And if it isn't, you really should add this as the last parameter otherwise you are breaking api for existing tests.

**Comment by okurz** [comment]
or better convert to using hash for optional parameters, e.g. see https://github.com/os-autoinst/os-autoinst/pull/502

**Comment by dzedro** [comment]
expect_not_found is doing the same

**Pull request closed without merging**
