### PR TITLE
Drop hmp socket and wrap every hmp command into a qmp command

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
@richiejp  If you change boot.pm in the fullstack test to be a milestone test, the error message changes at least :)

In master:
```
[Mon Dec  4 12:13:40 2017] [15740:debug] Loading a VM snapshot lastgood
DIE ERROR: timeout reading hmp socket

 at /space/prod/os-autoinst/backend/baseclass.pm line 80.
        backend::baseclass::die_handler("ERROR: timeout reading hmp socket\x{a}") called at /space/prod/os-autoinst/backend/qemu.pm line 905
        backend::qemu::_read_hmp(backend::qemu=HASH(0x55f159459b28)) called at /space/prod/os-autoinst/backend/qemu.pm line 973
        backend::qemu::_send_hmp(backend::qemu=HASH(0x55f159459b28), "loadvm lastgood") called at /space/prod/os-autoinst/backend/qemu.pm line 258
        backend::qemu::load_snapshot(backend::qemu=HASH(0x55f159459b28), HASH(0x55f15a70da08)) called at /space/prod/os-autoinst/backend/baseclass.pm line 75
        backend::baseclass::handle_command(backend::qemu=HASH(0x55f159459b28), HASH(0x55f15a761380)) called at /space/prod/os-autoinst/backend/baseclass.pm line 436
        backend::baseclass::check_socket(backend::qemu=HASH(0x55f159459b28), IO::Handle=GLOB(0x55f15939fa38)) called at /space/prod/os-autoinst/backend/qemu.pm line 1000
        backend::qemu::check_socket(backend::qemu=HASH(0x55f159459b28), IO::Handle=GLOB(0x55f15939fa38), 0) called at /space/prod/os-autoinst/backend/baseclass.pm line 208
        eval {...} called at /space/prod/os-autoinst/backend/baseclass.pm line 156
        backend::baseclass::run_capture_loop(backend::qemu=HASH(0x55f159459b28)) called at /space/prod/os-autoinst/backend/baseclass.pm line 129
        backend::baseclass::run(backend::qemu=HASH(0x55f159459b28), 5, 8) called at /space/prod/os-autoinst/backend/driver.pm line 85
        backend::driver::start(backend::driver=HASH(0x55f15963f5f0)) called at /space/prod/os-autoinst/backend/driver.pm line 48
        backend::driver::new("backend::driver", "qemu") called at /space/prod/os-autoinst/isotovideo line 211
        main::init_backend() called at /space/prod/os-autoinst/isotovideo line 280
[Mon Dec  4 12:13:41 2017] [15746:debug] waitpid for 15758 returned 15758
last frame
[Mon Dec  4 12:13:41 2017] [15746:debug] QEMU: qemu-system-i386: util/qemu-thread-posix.c:397: qemu_event_set: Assertion `ev->initialized' failed.
```

When using qmp:

```
[Mon Dec  4 12:16:47 2017] [16052:debug] Loading a VM snapshot lastgood
[Mon Dec  4 12:16:47 2017] [16058:debug] EVENT {"timestamp":{"microseconds":818141,"seconds":1512386207},"event":"STOP"}
[Mon Dec  4 12:16:49 2017] [16058:debug] sysread failed: Connection reset by peer
Use of uninitialized value in string ne at /space/prod/os-autoinst/backend/qemu.pm line 268.
DIE Can't syswrite(IO::Socket::UNIX=GLOB(0x563b1799b928), <BUFFER>): Broken pipe at /space/prod/os-autoinst/backend/qemu.pm line 857

 at /space/prod/os-autoinst/backend/baseclass.pm line 80.
        backend::baseclass::die_handler(autodie::exception=HASH(0x563b17a3ad30)) called at (eval 176) line 34
        backend::qemu::__ANON__(IO::Socket::UNIX=GLOB(0x563b1799b928), "{\"execute\":\"stop\"}\x{a}") called at /space/prod/os-autoinst/backend/qemu.pm line 857
        backend::qemu::handle_qmp_command(backend::qemu=HASH(0x563b166d1c90), HASH(0x563b17a3ae20)) called at /space/prod/os-autoinst/backend/qemu.pm line 271
        backend::qemu::load_snapshot(backend::qemu=HASH(0x563b166d1c90), HASH(0x563b177af060)) called at /space/prod/os-autoinst/backend/baseclass.pm line 75
        backend::baseclass::handle_command(backend::qemu=HASH(0x563b166d1c90), HASH(0x563b17a4bfc0)) called at /space/prod/os-autoinst/backend/baseclass.pm line 436
        backend::baseclass::check_socket(backend::qemu=HASH(0x563b166d1c90), IO::Handle=GLOB(0x563b1778a678)) called at /space/prod/os-autoinst/backend/qemu.pm line 922
        backend::qemu::check_socket(backend::qemu=HASH(0x563b166d1c90), IO::Handle=GLOB(0x563b1778a678), 0) called at /space/prod/os-autoinst/backend/baseclass.pm line 208
        eval {...} called at /space/prod/os-autoinst/backend/baseclass.pm line 156
        backend::baseclass::run_capture_loop(backend::qemu=HASH(0x563b166d1c90)) called at /space/prod/os-autoinst/backend/baseclass.pm line 129
        backend::baseclass::run(backend::qemu=HASH(0x563b166d1c90), 5, 8) called at /space/prod/os-autoinst/backend/driver.pm line 85
        backend::driver::start(backend::driver=HASH(0x563b16950f80)) called at /space/prod/os-autoinst/backend/driver.pm line 48
        backend::driver::new("backend::driver", "qemu") called at /space/prod/os-autoinst/isotovideo line 211
        main::init_backend() called at /space/prod/os-autoinst/isotovideo line 280
[Mon Dec  4 12:16:49 2017] [16058:debug] waitpid for 16070 returned 16070
last frame
[Mon Dec  4 12:16:49 2017] [16058:debug] QEMU: qemu-system-i386: util/qemu-thread-posix.c:397: qemu_event_set: Assertion `ev->initialized' failed.
```

**Comment by coolo** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1508799 - fixed for 2.11

**Comment by coolo** [comment]
I would actually merge this, but I fear we need some staging tests for it

**Comment by foursixnine** [comment]
Let’s kick it :)

**Comment by richiejp** [comment]
OK, I have updated my bug report on the same issue: https://bugzilla.opensuse.org/show_bug.cgi?id=1071032

**Comment by coolo** [comment]
So let's take it - won't deploy on christmas party night anyway. And we can revert if it turns out very problematic on some qemu versions.

**Pull request merged**
