### PR TITLE
Use subrepo for update-deps script

### PR DESCRIPTION
**Pull request by perlpunk**
Please see the README for info and instructions:
https://github.com/os-autoinst/os-autoinst-common/blob/master/README.md

This PR creates a subrepo at `external/os-autoinst-common/`
`tools/update-deps` is replaced with a symlink to `external/os-autoinst-common/tools/update-deps`.

See also https://github.com/os-autoinst/openQA/pull/3323 (merged)

Issue: https://progress.opensuse.org/issues/70654

### CODE REVIEW

**Comment by Martchus** [comment]
Looks generally good but the first commit message title should be simplified. I also think that the directory name `ext` doesn't really speak for itself. Maybe `external` which would at lest not be ambiguous? Or simply `subrepos`? Or just omit that extra directory level and have a directory `common` directly on the top-level?

**Comment by perlpunk** [comment]
I moved the directory to top: `os-autoinst-common/`

**Comment by perlpunk** [comment]
For some reason the `.gitrepo` file still says the branch is `dev`. Will look into it

**Review by okurz — CHANGES_REQUESTED** [review]
I am reverting my approval because I liked your previous directory name selection better. Same as Martchus I suggest `external/` as top folder to state the origin of the code better than just "os-autoinst-common".

**Comment by perlpunk** [comment]
@okurz then we have a conflict.
@kraih suggested `os-autoinst-common` in the top folder.
Not sure how to proceed if we can't resolve this.
Who is going to decide?

**Comment by perlpunk** [comment]
@kalikiana @okurz @kraih @Martchus please comment only in https://github.com/os-autoinst/openQA/pull/3323

**Comment by perlpunk** [comment]
https://github.com/os-autoinst/openQA/pull/3323 has been merged, and I updated this with the `external` directory.

**Review by okurz — APPROVED** [review]

**Pull request merged**
