### PR TITLE
Query vars.json of another job (POO#14306)

### PR DESCRIPTION
**Pull request by nadvornik**
Usage:

use mmapi;
my $parents = get_parents();
my $vars = get_job_autoinst_vars($parents->[0]);
print $vars->{WORKER_ID}

The function returns current content of vars.json. It can be updated by calling bmwqemu::save_vars() if needed.

### CODE REVIEW

**Comment by coolo** [comment]
As you're adding it to the API you need to provide some kind of API documentation. How to use the function, in what contexts. What to expect, ... 

Similiar to what you put in the commit log

**Comment by nadvornik** [comment]
It will be separate pull request on openQA repo

**Comment by coolo** [comment]
I don't like this discrepancy between testapi and mmapi. Defining the scope of multi machine testing is most likely not relevant for POD, but the expected arguments can very well live in the code directly.

**Comment by jerrytt** [comment]
job_id = 315 
url = http://linux-j7uw:20033/dwgYAut1bZujCa1Q

Mojo::Message::Response can not get response .

Use of uninitialized value in numeric eq (==) at /usr/lib/os-autoinst/mmapi.pm line 212.
Use of uninitialized value in concatenation (.) or string at /usr/lib/os-autoinst/mmapi.pm line 216.

The reason is the local dns does not work correctly . 

after replace http://linux-j7uw:20033/dwgYAut1bZujCa1Q ==> http://localhost:20033/dwgYAut1bZujCa1Q

I can get the expect result :)

**Comment by nadvornik** [comment]
IMHO this is a problem of host network configuration.

**Pull request merged**
