### PR TITLE
Delete obsolete automatic denting on needle name

### PR DESCRIPTION
**Pull request by okurz**
bnc# is obsolete and we have workaround property which should be used for
this.

### CODE REVIEW

**Comment by coolo** [comment]
did you check all bnc* have a workaround property?

**Comment by okurz** [comment]
> did you check all bnc* have a workaround property?

no

**Comment by sysrich** [comment]
> no

then I think this PR needs to be reconsidered

-1

**Comment by okurz** [comment]
IMHO you both wasted time to write your comments when it would be faster to check the existance of any needle in openSUSE / SLE repo with name "*bnc*". I checked, there are *none*, so the PR is safe for use. And I am sure fedora does not care about needles with "bnc" in name.

**Comment by coolo** [comment]
see? now you checked what I asked you for. So no time wasted.

**Comment by okurz** [comment]
On Thursday, 9 February 2017 07:07:56 CET Stephan Kulow wrote:
> see? now you checked what I asked you for. So no time wasted.

The initial answer "no" was less work then checking. The statement hidden 
inside there was "… and we should not care for various reasons, bnc# being 
outdated is just one"

**Pull request merged**
