### PR TITLE
Use more robust QMP snapshot save command instead of HMP

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
for @foursixnine to continue with, cherry pick the commit or something

**Comment by okurz** [comment]
@coolo @foursixnine I would have expected this change to be incorporated faster to fix annoying https://progress.opensuse.org/issues/19586 . I know it's not complete (only savevm replaced) but it should help nevertheless. Care to merge and deploy it?

**Comment by coolo** [comment]
the message in the PR is 'for @foursixnine to continue with' - why would I merge it, leave alone deploy

**Comment by foursixnine** [comment]
I wouldn't merge either :), since we have a nice mix of different versions of qemu this has to be tested well before deploying.

**Comment by okurz** [comment]
The PR description is actually empty only the second comment mentions "to continue with…". There is a fallback to HMP in case QMP does not work. I tested it locally with qemu-2.6 and it still does what it should and how it did in before.

**Comment by mnowaksuse** [comment]
I actually had the patch deployed to my openQA instance, where I saw the problem sporadically and I noticed it was not effective. Seen it fail once at least. What actually worked was reducing VM's memory from 4 to 2 gigs, then snapshot save worked.

**Comment by coolo** [comment]
I actually dare to claim that any sync call will not help the issue - because the timeout happens between test process and backend.

**Comment by okurz** [comment]
Sure, I don't think it will fix the issue but be a more robust approach meant for machine interfacing. Also qemu developers don't want to help as long as we use HMP here. Also I don't expect it to change any problems on x86_64 but only on aarch64 where we saw the original problem.

**Pull request closed without merging**
