### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by grisu48**
There is a zero too much

### CODE REVIEW

**Comment by okurz** [comment]
Let's pretend this never happened ;)

**Comment by perlpunk** [comment]
Why was this merged although the tests failed?
https://github.com/os-autoinst/os-autoinst/actions/runs/6259351724/job/16995179846
```
: 
7: #   Failed test 'No changed files after '/usr/bin/ninja update-deps''
7: #   at ./xt/27-make-update-deps.t line 25.
7: #  M cpanfile
7: # Looks like you failed 1 test of 2.
7: [09:01:06] ./xt/27-make-update-deps.t .............................
```

**Comment by perlpunk** [comment]
#2367 for a fix

**Comment by okurz** [comment]
> Why was this merged although the tests failed? https://github.com/os-autoinst/os-autoinst/actions/runs/6259351724/job/16995179846

I suspected a delayed problem with spurt/spew and invalid circleCI cache which obviously is a very stupid assumption given that os-autoinst does not use circleCI, shame on me

**Pull request merged**
