### PR TITLE
Fix zkvm serial

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by okurz** [comment]
-1. I think the behaviour is ok to skip saving a vm but I would much more prefer to have a refactoring on the names. It should ignore "saving a VM" if asked. Failing is the correct behaviour. Maybe "save_snapshot" would be better which can then (silently) fail. "load_snapshot" would then tell in a log message that there is no snapshot and starts from scratch instead.

**Comment by coolo** [comment]
how is save_snapshot and save_vm different beside the name?

**Comment by okurz** [comment]
not at all. It's all about good names

**Comment by coolo** [comment]
http://refactoring.com/catalog/renameMethod.html is even in the catalogue ;)

**Comment by okurz** [comment]
exactly. http://clean-code-developer.de/die-grade/roter-grad/#Einfache_Refaktorisierungsmuster_anwenden
I can bring you the red wristband tomorrow

**Pull request merged**
