### PR TITLE
[NEEDHELP] Fix usb-kbd 'key-event-full'

### PR DESCRIPTION
**Pull request by Soulofdestiny**
See last comment in https://progress.opensuse.org/issues/12250

### CODE REVIEW

**Comment by Soulofdestiny** [comment]
I'm definitely not sure about this, so I'm asking you to help me with that :)
Unfortunately I can't set labels

**Comment by okurz** [comment]
seems like a good idea but needs recent qemu version. I guess we should check on overdrive2 and malbec if their qemu supports this first. I would suggest to build a check into the backend to check version of qemu first before trying this.

**Comment by Soulofdestiny** [comment]
sounds like a good idea, yes
i checked overdrive and malbec - the versions differ, but on overdrive the version is new enough to support this

**Comment by coolo** [comment]
this is definitely wrong. 200 ms is an eternity. And we already send the keys delayed.

**Pull request closed without merging**
