### PR TITLE
Splitting the s390 backend into top level consoles

### PR DESCRIPTION
**Pull request by coolo**
This is still not finished as the consoles use things out of "PARMFILE", which shouldn't even exist.

But for that we need to change the tests to create the parm file itself - and pass host name to the console instead of relying on the backend to know where to connect ssh to.

The IPMI backend is changed too to use a local xterm too. I would like to see this merged and deployed/debugged in production.

### CODE REVIEW

**Comment by coolo** [comment]
And while I hacked the ipmi and s390 backend, I found (and fixed) several bugs in the VNC implementation ;)

**Comment by okurz** [comment]
When removing the vbox backend, the documentation should be adjusted, too. See https://github.com/os-autoinst/os-autoinst/blob/master/INSTALL.asciidoc

**Comment by coolo** [comment]
I would remove the complete documentation - our documentation lives in openQA repo

**Comment by coolo** [comment]
thanks for your reviews - I will cleanup the documentation in a followup PR. there is more to remove ;(

**Pull request merged**
