### PR TITLE
Add lockapi::barrier interface

### PR DESCRIPTION
**Pull request by aaannz**
- barrier_create($name, $tasks)
- barrier_wait($name) and barrier_try_wait (latter one to enable testability)
- barrier_destroy($name)

### CODE REVIEW

**Comment by okurz** [comment]
@dzyuzin is this what you had in mind, too?

**Comment by dzyuzin** [comment]
I'll rewrite HA tests to use barriers when I have time, and check if it works :)

**Comment by sysrich** [comment]
@dzyuzin - so, from a design perspective, you'd consider this something we should merge?

**Comment by aaannz** [comment]
Once merged, current HA tests can start to fail or generate warnings about redefined subroutines as @dzyuzin in the meantime implemented his helpers with the same names. Easy to fix, just informing.

**Comment by coolo** [comment]
can someone prep a PR for the tests to change the names of @dzyuzin 's helpers to avoid a race?

**Comment by dzyuzin** [comment]
All HA tests work fine with new lockAPI, this can be merged with https://github.com/os-autoinst/os-autoinst-distri-opensuse/issues/1878

**Pull request merged**
