### PR TITLE
Reformat with latest version of perltidy

### PR DESCRIPTION
**Pull request by Martchus**

### CODE REVIEW

**Comment by okurz** [comment]
If you want that then I think you need to update https://github.com/os-autoinst/os-autoinst/blob/master/cpanfile#L53 where we hardcode the version of perltidy. I wonder, why do you do this? To fix the new tidy problems in the openQA repo? Actually that could help me because I also have a failing test in https://travis-ci.org/okurz/openQA/jobs/467969386 but when we hardcode the version in os-autoinst I think we should do the same for openQA instead?

**Comment by Martchus** [comment]
> where we hardcode the version of perltidy

I wasn't aware of that. I wanted to fix the same problem we see in the openQA repository here, too. Apparently it is not the case due to hard-coding the version.

> I wonder, why do you do this?

It would still make sense to apply the latest tidy for consistency with openQA where we already use it.

> we hardcode the version in os-autoinst I think we should do the same for openQA instead?

Too late. I wouldn't undo all those changes in openQA again. Besides, code formatted with the new tidy version actually looks better.

It also makes sense to use the latest perl tidy because sooner or later distributions will ship that version and it would be additional effort for developers to get an older version.

**Comment by foursixnine** [comment]
@Martchus we could bring the change to the same as openQA. I think we stick to it, because it was/would and will affect os-autoinst-distri-opensuse. 

Also we had a lot of surprises of stuff failing due to tidy version changing (and last change prior to the fixed version, broke us for some time until we figured out https://github.com/os-autoinst/os-autoinst/pull/927).

**Comment by Martchus** [comment]
I updated the PR. It now hardcodes the new version which is also used in openQA. There we should hardcode that version, too (see https://github.com/os-autoinst/openQA/pull/1929).

**Comment by mitiao** [comment]
Does it need to add new version of perltidy in os-autoinst-distri-opensuse? since @GraceWang571 got travis fail:
https://travis-ci.org/os-autoinst/os-autoinst-distri-opensuse/jobs/470321811

**Comment by okurz** [comment]
Ah, this got merged. I think, yes, everybody needs to update the version of os-autoinst checked out for the use of perltidy in tests

**Pull request merged**
