### PR TITLE
Add a version route to commands

### PR DESCRIPTION
**Pull request by coolo**
curl -s
http://localhost:20113/98Xoquw0SPu7So7v/isotovideo/version | json_pp
{
   "version" : 6,
   "test_git_hash" : "5c4b7d1bc8be0b7c4a3a5bb6bc128dd6d34ee1b7"
}

The 6 is a random number, but it will increase and the worker will
require a minium version of it.

And it can transmit the test_git_hash to the webui so it can render the
correct sources even before the final vars.json is uploaded

### CODE REVIEW

**Comment by okurz** [comment]
* typo in commit message: minium
* Add the test to the Makefile?

**Comment by coolo** [comment]
I wasn't even aware we have a fixed list in the Makefile. fixed both now

**Comment by okurz** [comment]
fails now because can't find commands.pm. Add

```perl
BEGIN {
    unshift @INC, '..';
}
```

to 07-commands.pl

Ugly, yes. should be prove-ived

**Comment by okurz** [comment]
After that, LGTM

**Comment by coolo** [comment]
the problem we saw while deploying was btw not a minimum version problem, but a maximum. I.e. we the worker will have to restart itself when the os-autoinst version changed

**Pull request merged**
