### PR TITLE
testapi: add `check_type_string`, with screen change checking

### PR DESCRIPTION
**Pull request by AdamWill**
this adds a new `check_type_string` function, which basically
just does `type_string`, but waits for the screen to change
every few characters. You can configure how many characters
to type per `wait_still_screen` with the `size` parameter. I
wrote this to try and mitigate an issue we are having where
Fedora tests occasionally seem to exhaust the VM's input buffer
and thus miss characters (or repeat a character a bunch of
times, if the VM happens to get a key_down event but not the
key_up event), but it seems generally useful and may as well go
in testapi, I think.

### CODE REVIEW

**Comment by coolo** [comment]
I would prefer this implemented as option to type_string and implemented directly in the backend

**Comment by coolo** [comment]
type_string 'hallo', max_interval => 10, wait_screen_changes => 3

**Comment by AdamWill** [comment]
well, the problem with doing it that way is you can't use `wait_still_screen`, since that's in `testapi`. You'd have to re-implement it at the backend level. IIRC anyway...

**Comment by coolo** [comment]
That's a bit too much refactoring - but IMO at least make it part of the type_string api instead of having yet another function

**Comment by AdamWill** [comment]
ok, will do tomorrow.

**Pull request merged**
