### PR TITLE
Add support for <disk device="cdrom" ...> to svirt

### PR DESCRIPTION
**Pull request by mnowaksuse**
This adds support for cdroms on svirt hypervisors (e.g. for installation) and boot order of device.

Verification run: http://assam.suse.cz/tests/2834.
Required for: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1755.

### CODE REVIEW

**Comment by mnowaksuse** [comment]
@Soulofdestiny & @mimi1vx This may affect you.

**Comment by Soulofdestiny** [comment]
lgtm, should not affect zKVM testing

**Comment by aaannz** [comment]
:+1:

**Comment by mimi1vx** [comment]
Lgtm

**Pull request merged**
