### PR TITLE
Update Perl::Tidy to 20200619

### PR DESCRIPTION
**Pull request by Martchus**

### CODE REVIEW

**Comment by okurz** [comment]
well, premature merge. We got that tested out then as well :D

**Comment by okurz** [comment]
@Martchus next time if you want to prevent merge use either one of the terms "WIP", "Work in progress" or :construction: in the pull request title. Maybe the label "notready" also works.

**Comment by Martchus** [comment]
I haven't thought about an immediate approval. Intuitively I didn't make it a draft or use "WIP" because I don't expect further work to be done. It would be good to know whether "notready" works.

Since people using Leap and our devel repo actually have this version and TW users can simply install that single package from `devel:languages:perl` so this is likely not a big deal.

**Comment by okurz** [comment]
yes, sure. Should not be a big deal and hopefully also no deal with any next Tumbleweed snapshot. The perl tidy changes are always disruptive for other reasons still :(

**Pull request merged**
