### PR TITLE
developer mode: versioning, pause on check_screen timeout

### PR DESCRIPTION
**Pull request by Martchus**
* os-autoinst counterpart of https://github.com/os-autoinst/openQA/pull/1899
* builds on top of https://github.com/os-autoinst/os-autoinst/pull/1067

### CODE REVIEW

**Comment by okurz** [comment]
hm, the coverage decrease in https://codecov.io/gh/os-autoinst/os-autoinst/pull/1068/src/OpenQA/Isotovideo/CommandHandler.pm looks valid to me, can you crosscheck?

**Comment by Martchus** [comment]
This is still WIP. Please focus on reviewing https://github.com/os-autoinst/os-autoinst/pull/1067 first :-)

**Comment by Martchus** [comment]
only merge and deploy in sync with https://github.com/os-autoinst/openQA/pull/1899

**Comment by Martchus** [comment]
This fails only due to perlcritic. When running the perlcritic test locally one can see that it only complains about code which I did *not* touch. So the failing test is unrelated and maybe this is fixed by https://github.com/os-autoinst/os-autoinst/pull/1070.

**Comment by okurz** [comment]
+1

**Comment by okurz** [comment]
Could you rebase after https://github.com/os-autoinst/os-autoinst/pull/1070 was merged?

**Comment by Martchus** [comment]
I rebased and ran `PERL5LIB=tools/lib/perlcritic:$$PERL5LIB perlcritic --gentle --include Perl::Critic::Policy::HashKeyQuote --include Perl::Critic::Policy::ConsistentQuoteLikeWords .` locally. It didn't detect any further problems (did I invoke perlcritic correctly?).

**Pull request merged**
