### PR TITLE
Update tidy to 20220613

### PR DESCRIPTION
**Pull request by okurz**
Also see related os-autoinst-distri-opensuse change
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15178

### CODE REVIEW

**Review by perlpunk — CHANGES_REQUESTED** [review]
The commit and title is a bit misleading.
I guess you meant `s/20220706/20220613/`

**Comment by Martchus** [comment]
And shouldn't this be updated through the YAML file?

**Comment by okurz** [comment]
err, wait

**Comment by okurz** [comment]
> The commit and title is a bit misleading. I guess you meant `s/20220706/20220613/`

done

> And shouldn't this be updated through the YAML file?

done

Sorry. This was me trying to be quick while in a meeting, bad idea :)

**Review by perlpunk — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Pull request merged**
