### PR TITLE
Remove redundant pair of parentheses

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by sysrich** [comment]
:+1:

**Comment by coolo** [comment]
sorry for the Mergatio praecox

**Comment by coolo** [comment]
What's interesting: perlcritic has no warning about *that* problem ;)

```
Subroutine "write_crash_file" does not end with "return" at line 279, column 1.  See page 197 of PBP.  (Severity: 4)
Builtin function called with parentheses at line 280, column 6.  See page 13 of PBP.  (Severity: 1)
Useless interpolation of literal string at line 280, column 19.  See page 51 of PBP.  (Severity: 1)
File handle for "print" or "printf" is not braced at line 281, column 5.  See page 217 of PBP.  (Severity: 1)
Return value of flagged function ignored - print at line 281, column 5.  See pages 208,278 of PBP.  (Severity: 1)
```

**Comment by okurz** [comment]
@coolo you wanna go "perlcritic --brutal"? Let's see how far we can get :-)

**Comment by coolo** [comment]
I don't, I just wondered if perlcritic would have found it

**Pull request merged**
