### PR TITLE
Relax a little

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
This is what I'm testing atm

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
I changed the numbers a bit. I fear 500 kps are a bit too agressive.

**Comment by coolo** [comment]
(even in my testing it was pretty fine)

**Comment by coolo** [comment]
btw: we might want to make the big type_string optional in normal testing. it's a bit excessive :)

**Comment by okurz** [comment]
When you tested and it was fine, why the limit? 
We can still make it less aggressive whenever we encounter a problem and who would ever test more with a more aggressive setting?

**Comment by coolo** [comment]
Call it guts felling, call it experience. And as this morning I'm reminded on "QEMU: usb-kbd: warning: key event queue full" (with the old default) - so we have platforms where even the old 15 kps are a problem :(

**Pull request merged**
