### PR TITLE
Move key_round to testapi and renamed it to send_key_until_needlematch

### PR DESCRIPTION
**Pull request by nilxam**
Move key_round() to testapi from opensusebasetest, and renamed it to send_key_if_tag_unmatch(), action#7944

### CODE REVIEW

**Comment by coolo** [comment]
I don't think unmatch is a word. @sysrich ?

**Comment by coolo** [comment]
and the if is wrong too - as it does it not just once but repeatedly.

**Comment by nilxam** [comment]
How about send_key_until_tag_matched() ?

**Comment by sysrich** [comment]
unmatch can be a word.. like undo, so it implies an 'action' note a 'state'.

send_key_until_needlematch?
send_key_until_match?
send_key_until_needle?
send_key_until?

repeat_key_until?
repeat_key?

**Comment by nilxam** [comment]
updated with named send_key_until_needlematch

**Pull request merged**
