### PR TITLE
Format using Perl::Tidy 20190601

### PR DESCRIPTION
**Pull request by Martchus**
For consistency with https://github.com/os-autoinst/openQA/pull/2095

### CODE REVIEW

**Comment by okurz** [comment]
just keep in mind that os-autoinst-distri-opensuse uses the tidy from os-autoinst hence you should ensure that every QA engineer has access to the corresponding tidy version

**Comment by foursixnine** [comment]
@Martchus @okurz check linked pr.

**Comment by okurz** [comment]
on my openSUSE Leap 15.1 I do not yet have perl-Perl-Tidy-2019… from RPM packages so others might have a problem as well. I mean, I have it from cpanm but we should be nice to other people

**Comment by Martchus** [comment]
We should not require `cpanm`. I'll add perl-Perl-Tidy to our repo for Leap 15.1 as we have it already for Leap 15.0. I guess we should also wait for Tumbleweed (the latest version is in Factory but seems not published yet).

**Comment by kraih** [comment]
For future reference i made [a gist](https://gist.github.com/kraih/01ee1d7900c8bf776b93e7652b84f519) with instructions for how to use `cpanm` to temporarily install and use any version of perltidy in a local lib should the need arise.

**Comment by Martchus** [comment]
@kraih I turned it into scripts which are easy enough to work with so I can remember their usage: https://github.com/Martchus/openQA-helper#installing-a-custom-version-of-perl-dependencies-like-perltidy

**Comment by Martchus** [comment]
Tumbleweed has this tidy version now and we have it in our devel:openQA Leap repos. So I'd say this should be merged now.

**Pull request merged**
