### PR TITLE
add an option to upload_logs to avoid dying on failure

### PR DESCRIPTION
**Pull request by AdamWill**
in Fedora we use upload_logs a lot in post-fail hooks, and in
some cases the file may not exist. For instance, anaconda
creates lots of log files, some of which may not exist in some
circumstances. We would like to just be able to try and upload
them all but not have the post-fail hook die if any of them
does not exist, instead of having to test for each file's
existence before uploading it, or have a bunch of conditionals
that magically know which log files will exist in which state.

### CODE REVIEW

**Comment by AdamWill** [comment]
I'm testing this right now. What's that you say? Test first *then* submit a PR? Nahhh, that doesn't sound like fun...

**Comment by AdamWill** [comment]
welp, looks like it works: compare https://openqa.fedoraproject.org/tests/14834 (sad! missing log files! post fail hook died half way through when `/tmp/dnf.log` didn't exist!) to https://openqa.stg.fedoraproject.org/tests/15371 (happiness! all the logs are there! we don't care about stupid dnf!)

the weird behaviour on the very last log file is just because I made a stupid typo when editing that file's `upload_logs` command and put the `, 1` in the filename, heh.

**Comment by coolo** [comment]
yeah, but I don't like the ,1 - wherever we have this in a API the test writers tend to just copy&paste this magic number without knowing what it does (see type_string and send_key ). Better have a named parameter as we added for type_string and as discussed in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/1069

**Comment by AdamWill** [comment]
hehe, I can believe it =) OK, will update that soon. thanks.

**Comment by AdamWill** [comment]
How does that look?

**Comment by AdamWill** [comment]
oh perltidy, why must you.

**Comment by coolo** [comment]
do your friends know what kind of perl hacker you became? :)

**Comment by AdamWill** [comment]
@coolo you must NEVER TELL

actually i just ripped that off from `type_string`, sooo....

**Pull request merged**
