### PR TITLE
Update Perl::Tidy to 20230909

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by kalikiana** [comment]
```
Package 'perl-DBD-Pg-3.16.3' not found.
Package 'perl-Mojolicious-9.33' not found.
Package 'perl-Perl-Tidy-20230701' not found.
```

**Comment by grisu48** [comment]
Can we please make this happen soon? We are having complaining CI pipelines and things are getting quiet annoying ...

**Comment by okurz** [comment]
ok, let's go ahead without approval and the failing openQA fullstack test needs
* https://github.com/os-autoinst/openQA/pull/5305

**Comment by grisu48** [comment]
Thank you!

**Pull request merged**
