### PR TITLE
Only load snapshots if there is actually a next module

### PR DESCRIPTION
**Pull request by okurz**
After:
* https://github.com/os-autoinst/os-autoinst/pull/1987

### CODE REVIEW

**Comment by okurz** [comment]
This should be tested in a manual test with openQA where we actually load snapshots

**Comment by okurz** [comment]
@Mergifyio rebase

**Review by Martchus — COMMENTED** [review]
Looks generally good but yes, should be tested manually.

**Comment by okurz** [comment]
Deployed on openqaworker7.o.o with `curl -sS https://patch-diff.githubusercontent.com/raw/os-autoinst/os-autoinst/pull/1988.patch | patch -p1 --directory=/usr/lib/os-autoinst`

**Review by Martchus — APPROVED** [review]

**Review by mimi1vx — APPROVED** [review]

**Pull request merged**
