### PR TITLE
Sort out duplicate needles on multiple tags (poo#19210)

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/19210

### CODE REVIEW

**Comment by okurz** [comment]
Wanted to test on ppc64le but failed to build os-autoinst. Anyone wants to confirm it's fine? At least the local tests work.

**Comment by coolo** [comment]
it builds in obs

**Comment by coolo** [comment]
LGTM

**Comment by okurz** [comment]
uniq is not yet available in perl(List::Util) package on SLE 12 SP2. I will use List-MoreUtils and test

**Comment by okurz** [comment]
updated. See it in action in http://lord.arch/tests/6269#step/setup_zdup/1 vs. http://lord.arch/tests/6264#step/setup_zdup/1

**Pull request merged**
